### ISSUE TITLE
Transactions name doesn't have the router parent name

### ISSUE THREAD

**Issue by descampsk** [elastic/apm-agent-nodejs#1110]
**Describe the bug**
When i use routers, I don't have the parent name in the transaction name.

**To Reproduce**
I have the three following files:

```
#app.js 
var app = require('express')()  
app.use(require('./router))  
```

```
#router.js    
let router = Router()
router.use('/users', require('/users'))
```

and

```
#users.js    
let router = Router()
router.route('/:id').get(getUserById)
```

**Expected behavior**
The transaction name should be GET /users/:id but is actually GET /:id

**Environment (please complete the following information)**
- OS: linux
- Node.js version: 10.15.3
- APM Server version: last
- Agent version: 2.11.5
- Express:  4.17.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)

Do you need some additionnal informations ?

Thank you !

**Comment by watson** [comment]
I've not been able to reproduce the bug unfortunately.

Would it be possible for you to configure the agent with `logLevel: 'trace'`, start up your app and send a simple http request to `GET /users/42` and paste the resulting debug output here?

**Comment by descampsk** [comment]
I'm trying on a more complex env that the example i gave, maybe I have some configurations which change things ...

Here is the logs I have : 

```
NODE_ENV=production npm start

> core-manager@1.0.0 start /mnt/c/Programmation/antiopea/axiom/backend/core-manager
> node core-manager.js

2019-06-03 15:56:05 [info][core-manager/core-manager.js]: Core-manager is launched in production mode
agent configured correctly { pid: 3434,
  ppid: 3433,
  arch: 'x64',
  platform: 'linux',
  node: 'v10.15.3',
  agent: '2.11.5',
  ancestors:
   [ '/mnt/c/Programmation/antiopea/axiom/backend/core-manager/node_modules/elastic-apm-node/index.js',
     '/mnt/c/Programmation/antiopea/axiom/backend/core-manager/apm.js',
     '/mnt/c/Programmation/antiopea/axiom/backend/core-manager/core-manager.js',
     [length]: 3 ],
  startTrace:
   [ 'at Agent.start (/mnt/c/Programmation/antiopea/axiom/backend/core-manager/node_modules/elastic-apm-node/lib/agent.js:149:11)',
     'at awsHelper.getAwsSecretValue.then.secret (/mnt/c/Programmation/antiopea/axiom/backend/core-manager/apm.js:9:13)',
     'at process._tickCallback (internal/process/next_tick.js:68:7)',
     [length]: 3 ],
  main: 'core-manager.js',
  dependencies:
   { async: '^2.6.2',
     'aws-sdk': '^2.434.0',
     bcryptjs: '^2.4.3',
     'big-integer': '^1.6.43',
     'body-parser': '^1.18.3',
     compression: '^1.7.2',
     config: '^3.0.1',
     cors: '^2.8.5',
     'crypto-js': '^3.1.9-1',
     'elastic-apm-node': '^2.11.5',
     express: '^4.17.1',
     'express-mung': '^0.5.1',
     'fs-extra': '^7.0.1',
     glob: '^7.1.3',
     handlebars: '^4.1.2',
     helmet: '^3.15.1',
     'http-errors': '^1.7.2',
     jsonwebtoken: '^8.5.0',
     lodash: '^4.17.11',
     md5: '^2.2.1',
     'md5-file': '^4.0.0',
     mongodb: '^3.1.13',
     mongoose: '^5.4.14',
     'mongoose-autopopulate': '^0.9.1',
     multer: '^1.4.1',
     'multer-s3': '^2.9.0',
     nodemailer: '^6.1.0',
     passport: '^0.4.0',
     'passport-jwt': '^4.0.0',
     'socket.io': '^2.2.0',
     'socket.io-client': '^2.2.0',
     'socketio-jwt': '^4.5.0',
     'swagger-ui-express': '^4.0.2',
     uuid: '^3.3.2',
     validator: '^10.11.0',
     winston: '^3.2.1' },
  conf:
   { verifyServerCert: true,
     active: true,
     logLevel: 'trace',
     apiRequestSize: 786432,
     apiRequestTime: 10,
     stackTraceLimit: 50,
     captureExceptions: true,
     filterHttpHeaders: true,
     captureErrorLogStackTraces: 'messages',
     captureSpanStackTraces: true,
     captureBody: 'off',
     errorOnAbortedRequests: false,
     abortedErrorThreshold: 25,
     instrument: true,
     asyncHooks: true,
     sourceLinesErrorAppFrames: 5,
     sourceLinesErrorLibraryFrames: 5,
     sourceLinesSpanAppFrames: 0,
     sourceLinesSpanLibraryFrames: 0,
     errorMessageMaxLength: 2048,
     transactionMaxSpans: 500,
     transactionSampleRate: 1,
     serverTimeout: 30,
     disableInstrumentations: [ [length]: 0 ],
     containerId: undefined,
     kubernetesNodeName: undefined,
     kubernetesNamespace: undefined,
     kubernetesPodName: undefined,
     kubernetesPodUID: undefined,
     captureHeaders: true,
     metricsInterval: 30,
     usePathAsTransactionName: true,
     addPatch: undefined,
     globalLabels: undefined,
     serviceName: 'axiom-production',
     secretToken: 'XXXXX',
     serverUrl:
      'https://XXXXXX.apm.eu-west-1.aws.cloud.es.io:443',
     logger:
      { trace:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        debug:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        info:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        warn:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        error:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } },
        fatal:
         { [Function: log]
           [length]: 0,
           [name]: 'log',
           [prototype]: log { [constructor]: [Circular] } } },
     ignoreUrlStr: [ [length]: 0 ],
     ignoreUrlRegExp: [ [length]: 0 ],
     ignoreUserAgentStr: [ [length]: 0 ],
     ignoreUserAgentRegExp: [ [length]: 0 ],
     transport:
      { [Function: httpTransport]
        [length]: 2,
        [name]: 'httpTransport',
        [prototype]: httpTransport { [constructor]: [Circular] } },
     serverHost:
      'XXXXXXX.apm.eu-west-1.aws.cloud.es.io:443',
     serverPort: 443 } }
adding hook to Node.js module loader
2019-06-03 15:56:06 [debug][helpers/mongooseHelper.js]: Connecting to mongodb+srv://XXXXXX.mongodb.net/axiom?retryWrites=true ...
shimming https@10.15.3 module
shimming https.Server.prototype.emit function
shimming https.request function
shimming https.get function
no active transaction found - cannot build new span
intercepted call to https.request { id: null }
2019-06-03 15:56:06 [debug][helpers/mongooseHelper.js]: Database connection successful - XXXXXXX.mongodb.net/axiom?retryWrites=true
shimming http@10.15.3 module
shimming http.Server.prototype.emit function
shimming http.request function
shimming http.get function
shimming http.ServerResponse.prototype.writeHead function
shimming ws@6.1.4 module
shimming ws.prototype.send function
no active transaction found - cannot build new span
intercepted call to https.request { id: null }
2019-06-03 15:56:06 [info][core-manager/core-manager.js]: Server is listening on port 8080
intercepted request event call to http.Server.prototype.emit
start trace { trans: '3c674ac33dc28851',
  parent: undefined,
  trace: 'df4413d2213a7bf8a8dd37fe9b4de2a3',
  name: null,
  type: null }
2019-06-03 15:56:15 [info][core-manager/core-manager.js]: GET  /users/5cdac10070e9097f7da175e6 {} -
 [status - 200] {"success":true,"code":200}
setting transaction result { trans: '3c674ac33dc28851',
  parent: undefined,
  trace: 'df4413d2213a7bf8a8dd37fe9b4de2a3',
  result: 'HTTP 2xx' }
setting default transaction name: GET /:id { trans: '3c674ac33dc28851',
  parent: undefined,
  trace: 'df4413d2213a7bf8a8dd37fe9b4de2a3' }
sending transaction { trans: '3c674ac33dc28851',
  trace: 'df4413d2213a7bf8a8dd37fe9b4de2a3' }
ended transaction { trans: '3c674ac33dc28851',
  parent: undefined,
  trace: 'df4413d2213a7bf8a8dd37fe9b4de2a3',
  type: 'request',
  result: 'HTTP 2xx',
  name: 'GET /:id' }
no active transaction found - cannot build new span
intercepted call to https.request { id: null }
```

**Comment by descampsk** [comment]
Here is my apm config: 
```
        apm.start({
            // Override service name from package.json
            // Allowed characters: a-z, A-Z, 0-9, -, _, 
            // and space
            serviceName: `axiom-${process.env.NODE_ENV || 'dev'}`,
          
            // Use if APM Server requires a token
            secretToken: secretToken,
          
            // Set custom APM Server URL
            // Default: http://localhost:8200
            serverUrl: serverUrl,

            usePathAsTransactionName: true,

            logLevel: 'trace'
          })
```

**Comment by descampsk** [comment]
On the easy example I give, its working, I'm looking what others config I add until it won't work anymore.

**Comment by descampsk** [comment]
I found it  !!!

I had something like this : 

```
# app.js
var apm = require('elastic-apm-node')

awsHelper.getAwsSecretValue(apmAwsSecretName)
    .then(secret => {
        let secretToken = secret['apm-server-token']
        let serverUrl = secret['apm-server-url']
        apm.start({
            // Override service name from package.json
            // Allowed characters: a-z, A-Z, 0-9, -, _, 
            // and space
            serviceName: `axiom-${process.env.NODE_ENV || 'dev'}`,
          
            // Use if APM Server requires a token
            secretToken: secretToken,
          
            // Set custom APM Server URL
            // Default: http://localhost:8200
            serverUrl: serverUrl,

            usePathAsTransactionName: true,

            logLevel: 'trace'
          })
    })

app.liste(.....)
```

I think this asynchronous operation doesn't initialize right the apm module :(.

When i did : 

```
var apm = require('elastic-apm-node')

apm.start({
    // Override service name from package.json
    // Allowed characters: a-z, A-Z, 0-9, -, _, 
    // and space
    serviceName: `testing`,
  
    // Use if APM Server requires a token
    secretToken: "SECRET",
  
    // Set custom APM Server URL
    // Default: http://localhost:8200
    serverUrl: "https://XXXX.apm.eu-west-1.aws.cloud.es.io:443",

    usePathAsTransactionName: true,

    logLevel: 'trace'
  })
app.listen(')
```

It works.

So I need to retrieve my secret and launch the apm before creating the app.

Thanks for the help, and sorry for my own error :D

**Comment by watson** [comment]
No worries. Glad you found the issue and hopefully can work around it.

The reason why the agent doesn't support being started asynchronously is that it needs to hook into the `require` function in Node core to be able to hook into all modules that are loading. So if it's started later, it will miss important modules and no longer work as expected.
