### ISSUE TITLE
Test errors for mongodb-core when running in windows

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-nodejs#1453]
**Describe the bug**

When working on https://github.com/elastic/apm-agent-nodejs/pull/1393 I managed to get some kind of flakiness when running the tests for the mongodb-core.

  <details>
    <summary>Click to expand</summary>

```
[2019-10-11T10:59:33.825Z] running (cwd: ./): node --unhandled-rejections=strict test\instrumentation\modules\mongodb-core.js
[2019-10-11T10:59:35.202Z] TAP version 13
...
[2019-10-11T10:59:36.138Z] not ok 15 test exited without ending
[2019-10-11T10:59:36.138Z]   ---
[2019-10-11T10:59:36.138Z]     operator: fail
[2019-10-11T10:59:36.138Z]     at: process.<anonymous> (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\index.js:88:19)
[2019-10-11T10:59:36.138Z]     stack: |-
[2019-10-11T10:59:36.138Z]       Error: test exited without ending
[2019-10-11T10:59:36.138Z]           at Test.assert [as _assert] (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:225:54)
[2019-10-11T10:59:36.138Z]           at Test.bound [as _assert] (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:77:32)
[2019-10-11T10:59:36.138Z]           at Test.fail (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:318:10)
[2019-10-11T10:59:36.138Z]           at Test.bound [as fail] (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:77:32)
[2019-10-11T10:59:36.138Z]           at Test._exit (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:188:14)
[2019-10-11T10:59:36.138Z]           at Test.bound [as _exit] (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\lib\test.js:77:32)
[2019-10-11T10:59:36.138Z]           at process.<anonymous> (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1393\src\github.com\elastic\apm-agent-nodejs\node_modules\tape\index.js:88:19)
[2019-10-11T10:59:36.138Z]           at process.emit (events.js:210:5)
[2019-10-11T10:59:36.138Z]   ...
[2019-10-11T10:59:36.138Z] 
[2019-10-11T10:59:36.138Z] 1..15
[2019-10-11T10:59:36.138Z] # tests 15
[2019-10-11T10:59:36.138Z] # pass  14
[2019-10-11T10:59:36.138Z] # fail  1
```

  </details>

**To Reproduce**

- See [build 99](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1393/99/pipeline)

**Expected behavior**
[build 97](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1393/97/pipeline) worker as expected 

**Environment (please complete the following information)**

- OS: Windows 2019
- Node.js version: Nodejs 12.11.1
- APM Server version: `mocked`
- Agent version:

**Comment by trentm** [comment]
I haven't seen this error in CI tests in the ~2y I've been here.
