### ISSUE TITLE
 TypeError: Cannot add property elastic-apm-traceparent, object is not extensible

### ISSUE THREAD

**Issue by MattRiddell** [elastic/apm-agent-nodejs#1575]
**Describe the bug**

If a transaction exists when a phone call starts we crash.

```
stasis_start.js:46:21_________ Error answering:  TypeError: Cannot add property elastic-apm-traceparent, object is not extensible
    at Object.request (/NodeJSQueue/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:152:52)
    at createRequest (/NodeJSQueue/node_modules/shred/lib/shred/request.js:427:23)
    at new Request (/NodeJSQueue/node_modules/shred/lib/shred/request.js:79:3)
    at Shred.request (/NodeJSQueue/node_modules/shred/lib/shred.js:47:12)
    at ShredHttpClient.execute (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:1314:21)
    at SwaggerHttp.execute (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:1134:34)
    at new SwaggerRequest (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:1099:27)
    at SwaggerOperation.do (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:869:9)
    at SwaggerOperation.do (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:6:15)
    at SwaggerOperation.resource.(anonymous function) (/NodeJSQueue/node_modules/swagger-client/lib/swagger.js:759:23)
    at /NodeJSQueue/node_modules/ari-client/lib/resources.js:932:63
    at Promise._execute (/NodeJSQueue/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/NodeJSQueue/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/NodeJSQueue/node_modules/bluebird/js/release/promise.js:79:10)
    at Channel.callSwagger [as answer] (/NodeJSQueue/node_modules/ari-client/lib/resources.js:876:14)
    at Client.stasis_start (/NodeJSQueue/stasis_start.js:44:14)
    at Client.emit (events.js:198:13)
    at WebSocket.processMessage (/NodeJSQueue/node_modules/ari-client/lib/client.js:453:12)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/NodeJSQueue/node_modules/ari-client/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**To Reproduce**

Steps to reproduce the behavior: 

Write a program that uses Asterisk ARI for NodeJS.

If you start a transaction in the context of a call it crashes when it tries to answer the call.

If you remove APM everything works fine.

If you start an APM transaction at boot but nothing call related everything works fine.

```Javascript
channel_module.emitter.on('channelCreated', (event) => {
    let trans;
    try {
        trans = apm.startTransaction(event.channel.id, 'call');
    } catch ( e) {
        console.log(e);
    }
    
    transactions[event.channel.id] = trans;
    console.log("channelCreated", event);
});
```

**Expected behavior**

It doesn't crash.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 10.17.0
- APM Server version: Unknown
- Agent version: 3.1.0

**How are you starting the agent? (please tick one of the boxes)**

- [ X ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Had to add captureExceptions: false because otherwise it crashes on an unhandledException rather than catching it with my handler.

- Agent config options 
  <details>
    <summary>Click to expand</summary>

```javascript
 apm.start({
        // Use if APM Server requires a token
        secretToken: 'xx',
        captureExceptions: false,
        serverUrl:   'https://xx',
    });
```

  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

```
    "@pm2/io": "^4.3.2",
    "ari-client": "^2.2.0",
    "colors": "^1.3.3",
    "cross-env": "^5.2.1",
    "dotenv": "^8.2.0",
    "elastic-apm-node": "^3.1.0",
    "inquirer": "^6.3.1",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "inquirer-command-prompt": "0.0.8",
    "lodash": "^4.17.15",
    "mysql": "^2.16.0",
    "uuid": "^3.3.3",
    "websocket": "^1.0.28"
```
  </details>

**Comment by trentm** [comment]
Hi. I'm cleaning out some older issues.


In the older version of the agent (v3.1.0) the code that was throwing was the one marked "line 152" below:

```js
      // ...
      var parent = span || agent.currentTransaction
      if (parent && parent._context && shouldPropagateTraceContext(options)) {
        options.headers['elastic-apm-traceparent'] = parent._context.toString() // line 152
      }
```

If the given `options.headers` had been marked non-extensible via `Object.preventExtensions(options.headers)`
(see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible)
then this exception could have happened.

In the current agent version this is:

```js
      const parent = span || parentRunContext.currSpan() || parentRunContext.currTransaction()
      if (parent) {
        const headers = Object.assign({}, options.headers)
        parent.propagateTraceContextHeaders(headers, function (carrier, name, value) {
          carrier[name] = value
        })
        options.headers = headers
      }
```

which no longer is susceptible to this.
