### ISSUE TITLE
Linting stage is failling

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-nodejs#1591]
We have to review what is happening and fix it 

```
[2020-01-08T16:28:51.936Z] + npm run lint:commit
[2020-01-08T16:28:51.936Z] 
[2020-01-08T16:28:51.936Z] > elastic-apm-node@3.3.0 lint:commit /app
[2020-01-08T16:28:51.936Z] > test/lint-commits.sh
[2020-01-08T16:28:51.936Z] 
[2020-01-08T16:28:51.936Z] + [[ -n https://apm-ci.elastic.co/ ]]
[2020-01-08T16:28:51.936Z] ++ npm bin
[2020-01-08T16:28:51.936Z] + export PATH=/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2020-01-08T16:28:51.936Z] + PATH=/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2020-01-08T16:28:51.936Z] ++ pwd
[2020-01-08T16:28:51.936Z] + export HOME=/app
[2020-01-08T16:28:51.936Z] + HOME=/app
[2020-01-08T16:28:51.936Z] + [[ -z '' ]]
[2020-01-08T16:28:51.936Z] + commitlint --from=957658ad4a0ae92b70887ec3e32583e5f492a15f~1
[2020-01-08T16:28:52.201Z] /app/node_modules/@commitlint/cli/lib/cli.js:124
[2020-01-08T16:28:52.201Z] 	throw err;
[2020-01-08T16:28:52.201Z] 	^
[2020-01-08T16:28:52.201Z] 
[2020-01-08T16:28:52.201Z] Error: error: object directory /var/lib/jenkins/.git-references/apm-agent-nodejs.git/objects does not exist; check .git/objects/info/alternates.
[2020-01-08T16:28:52.201Z] 
[2020-01-08T16:28:52.201Z]     at DestroyableTransform._transform (/app/node_modules/git-raw-commits/index.js:83:30)
[2020-01-08T16:28:52.201Z]     at DestroyableTransform.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)
[2020-01-08T16:28:52.201Z]     at DestroyableTransform.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
[2020-01-08T16:28:52.202Z]     at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:405:139)
[2020-01-08T16:28:52.202Z]     at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:394:5)
[2020-01-08T16:28:52.202Z]     at DestroyableTransform.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:303:11)
[2020-01-08T16:28:52.202Z]     at Socket.ondata (_stream_readable.js:727:22)
[2020-01-08T16:28:52.202Z]     at Socket.emit (events.js:215:7)
[2020-01-08T16:28:52.202Z]     at addChunk (_stream_readable.js:309:12)
[2020-01-08T16:28:52.202Z]     at readableAddChunk (_stream_readable.js:286:13)
[2020-01-08T16:28:52.202Z] npm ERR! code ELIFECYCLE
[2020-01-08T16:28:52.202Z] npm ERR! errno 1
[2020-01-08T16:28:52.202Z] npm ERR! elastic-apm-node@3.3.0 lint:commit: `test/lint-commits.sh`
[2020-01-08T16:28:52.202Z] npm ERR! Exit status 1
[2020-01-08T16:28:52.202Z] npm ERR! 
[2020-01-08T16:28:52.202Z] npm ERR! Failed at the elastic-apm-node@3.3.0 lint:commit script.
[2020-01-08T16:28:52.202Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2020-01-08T16:28:52.202Z] 
[2020-01-08T16:28:52.202Z] npm ERR! A complete log of this run can be found in:
[2020-01-08T16:28:52.202Z] npm ERR!     /app/.npm/_logs/2020-01-08T16_28_52_128Z-debug.log
```

**Comment by v1v** [comment]
Solved with https://github.com/elastic/apm-agent-nodejs/pull/1654
