### ISSUE TITLE
[CI] Issue connecting to Elasticsearch on Jenkins on Windows

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1744]
When running the tests on Jenkins on Windows, I see a random connection error when the tests try to connect to the Elasticsearch cluster. The test always seems to fail during `node --unhandled-rejections=strict test\instrumentation\modules\elasticsearch.js`, but at different locations.

In each case, the error is something along the lines of:

```
TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://:undefined/_search/template
```

This is the URL to the Elastichsearch cluster that somehow is "undefined".

Here are two examples of such failures:

From https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1743/1/pipeline:
```
[2020-05-11T12:00:05.627Z] # client.ping with callback
[2020-05-11T12:00:05.627Z] internal/url.js:257
[2020-05-11T12:00:05.627Z]   throw new ERR_INVALID_URL(input);
[2020-05-11T12:00:05.627Z]   ^
[2020-05-11T12:00:05.627Z] 
[2020-05-11T12:00:05.627Z] TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://:undefined/
[2020-05-11T12:00:05.627Z]     at onParseError (internal/url.js:257:9)
[2020-05-11T12:00:05.627Z]     at new URL (internal/url.js:333:5)
[2020-05-11T12:00:05.627Z]     at exports.parseUrl (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\parsers.js:247:10)
[2020-05-11T12:00:05.627Z]     at exports.getHTTPDestination (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\context.js:14:48)
[2020-05-11T12:00:05.627Z]     at IncomingMessage.onEnd (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\http-shared.js:212:38)
[2020-05-11T12:00:05.627Z]     at IncomingMessage.elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-11T12:00:05.627Z]     at IncomingMessage.emit (events.js:322:22)
[2020-05-11T12:00:05.627Z]     at endReadableNT (_stream_readable.js:1187:12)
[2020-05-11T12:00:05.627Z]     at elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-11T12:00:05.627Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2020-05-11T12:00:05.627Z]   input: 'http://:undefined/',
[2020-05-11T12:00:05.627Z]   code: 'ERR_INVALID_URL'
[2020-05-11T12:00:05.627Z] }
[2020-05-11T12:00:05.627Z] C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\test\test.js:129
[2020-05-11T12:00:05.627Z]     if (err) throw err
[2020-05-11T12:00:05.627Z]              ^
[2020-05-11T12:00:05.627Z] 
[2020-05-11T12:00:05.627Z] Error: non-zero error code
[2020-05-11T12:00:05.627Z]     at ChildProcess.<anonymous> (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\test\test.js:37:19)
[2020-05-11T12:00:05.627Z]     at ChildProcess.emit (events.js:310:20)
[2020-05-11T12:00:05.627Z]     at maybeClose (internal/child_process.js:1021:16)
[2020-05-11T12:00:05.627Z]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
[2020-05-11T12:00:05.627Z]   code: 'ENONZERO',
[2020-05-11T12:00:05.627Z]   exitCode: 1
[2020-05-11T12:00:05.627Z] }
```

From https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1743/2/pipeline:
```
[2020-05-11T13:34:42.063Z] # client.searchTemplate with callback
[2020-05-11T13:34:42.063Z] internal/url.js:257
[2020-05-11T13:34:42.063Z]   throw new ERR_INVALID_URL(input);
[2020-05-11T13:34:42.063Z]   ^
[2020-05-11T13:34:42.063Z] 
[2020-05-11T13:34:42.063Z] TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://:undefined/_search/template
[2020-05-11T13:34:42.063Z]     at onParseError (internal/url.js:257:9)
[2020-05-11T13:34:42.063Z]     at new URL (internal/url.js:333:5)
[2020-05-11T13:34:42.063Z]     at exports.parseUrl (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\parsers.js:247:10)
[2020-05-11T13:34:42.063Z]     at exports.getHTTPDestination (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\context.js:14:48)
[2020-05-11T13:34:42.063Z]     at IncomingMessage.onEnd (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\http-shared.js:212:38)
[2020-05-11T13:34:42.063Z]     at IncomingMessage.elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-11T13:34:42.063Z]     at IncomingMessage.emit (events.js:322:22)
[2020-05-11T13:34:42.063Z]     at endReadableNT (_stream_readable.js:1187:12)
[2020-05-11T13:34:42.063Z]     at elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-11T13:34:42.063Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2020-05-11T13:34:42.063Z]   input: 'http://:undefined/_search/template',
[2020-05-11T13:34:42.064Z]   code: 'ERR_INVALID_URL'
[2020-05-11T13:34:42.064Z] }
[2020-05-11T13:34:42.064Z] C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\test\test.js:129
[2020-05-11T13:34:42.064Z]     if (err) throw err
[2020-05-11T13:34:42.064Z]              ^
[2020-05-11T13:34:42.064Z] 
[2020-05-11T13:34:42.064Z] Error: non-zero error code
[2020-05-11T13:34:42.064Z]     at ChildProcess.<anonymous> (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1743\src\github.com\elastic\apm-agent-nodejs\test\test.js:37:19)
[2020-05-11T13:34:42.064Z]     at ChildProcess.emit (events.js:310:20)
[2020-05-11T13:34:42.064Z]     at maybeClose (internal/child_process.js:1021:16)
[2020-05-11T13:34:42.064Z]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
[2020-05-11T13:34:42.064Z]   code: 'ENONZERO',
[2020-05-11T13:34:42.064Z]   exitCode: 1
[2020-05-11T13:34:42.064Z] }
```

ping @elastic/observablt-robots

**Comment by kuisathaverat** [comment]
How this URL is passed to the test?

**Comment by watson** [comment]
The changes in #1745, unfortunately, doesn't seem to have fixed the issue. The last few days I've seen random Windows failures like the one listed in this issue. The latest one being:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1756/1/pipeline

```
[2020-05-19T11:50:28.520Z] # client.searchTemplate with callback
[2020-05-19T11:50:28.520Z] internal/url.js:257
[2020-05-19T11:50:28.520Z]   throw new ERR_INVALID_URL(input);
[2020-05-19T11:50:28.520Z]   ^
[2020-05-19T11:50:28.520Z] 
[2020-05-19T11:50:28.520Z] TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://:undefined/_search/template
[2020-05-19T11:50:28.520Z]     at onParseError (internal/url.js:257:9)
[2020-05-19T11:50:28.520Z]     at new URL (internal/url.js:333:5)
[2020-05-19T11:50:28.520Z]     at exports.parseUrl (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\lib\parsers.js:247:10)
[2020-05-19T11:50:28.520Z]     at exports.getHTTPDestination (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\context.js:14:48)
[2020-05-19T11:50:28.520Z]     at IncomingMessage.onEnd (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\http-shared.js:212:38)
[2020-05-19T11:50:28.520Z]     at IncomingMessage.elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-19T11:50:28.520Z]     at IncomingMessage.emit (events.js:322:22)
[2020-05-19T11:50:28.520Z]     at endReadableNT (_stream_readable.js:1187:12)
[2020-05-19T11:50:28.520Z]     at elasticAPMCallbackWrapper (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\lib\instrumentation\index.js:309:27)
[2020-05-19T11:50:28.520Z]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[2020-05-19T11:50:28.520Z]   input: 'http://:undefined/_search/template',
[2020-05-19T11:50:28.520Z]   code: 'ERR_INVALID_URL'
[2020-05-19T11:50:28.520Z] }
[2020-05-19T11:50:28.520Z] C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\test\test.js:129
[2020-05-19T11:50:28.520Z]     if (err) throw err
[2020-05-19T11:50:28.520Z]              ^
[2020-05-19T11:50:28.520Z] 
[2020-05-19T11:50:28.520Z] Error: non-zero error code
[2020-05-19T11:50:28.520Z]     at ChildProcess.<anonymous> (C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-1756\src\github.com\elastic\apm-agent-nodejs\test\test.js:37:19)
[2020-05-19T11:50:28.520Z]     at ChildProcess.emit (events.js:310:20)
[2020-05-19T11:50:28.520Z]     at maybeClose (internal/child_process.js:1021:16)
[2020-05-19T11:50:28.520Z]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
[2020-05-19T11:50:28.520Z]   code: 'ENONZERO',
[2020-05-19T11:50:28.520Z]   exitCode: 1
[2020-05-19T11:50:28.521Z] }
script returned exit code 1[2020-05-19T11:50:28.711Z] JUnit archiving no yet in place
```

**Comment by v1v** [comment]
I'm adding more debug logs in the pipeline to see what's going on

**Comment by v1v** [comment]
@watson , I've just seen the error in the last [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/493/pipeline) but as far as I see the CI windows worker could ping the elasticsearch machine, not sure what else we can do, or whether iit's an infra issue or a flakiness in the test

**Comment by v1v** [comment]
I'll reopen it for the time being until we can clarify the above questions

**Comment by trentm** [comment]
@v1v Hi, I'm catching up... are we still running CI on Windows (at least for this repo)?

**Comment by trentm** [comment]
FWIW I haven't seen an error like this in CI for over a year (I've never seen it myself). I'll close for now. We can re-open or open new issues if there are Windows CI issues.
