### ISSUE TITLE
pg TAV test failures

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#1866]
Per https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/656/pipeline these TAV tests failed:

Node.js-8-pg
Node.js-10-pg
Node.js-12-pg
Node.js-13-pg

Note that "Node.js-14-pg" passed.

From the node v10 pg test log:

```
[2020-11-10T06:35:50.839Z] node_tests_1  | -- running test "node test/instrumentation/modules/pg/pg.js" with pg
[2020-11-10T06:35:50.839Z] node_tests_1  | /app/test/instrumentation/modules/pg/pg.js:469
[2020-11-10T06:35:50.839Z] node_tests_1  |           .then(function () {
[2020-11-10T06:35:50.839Z] node_tests_1  |            ^
[2020-11-10T06:35:50.839Z] node_tests_1  | 
[2020-11-10T06:35:50.839Z] node_tests_1  | TypeError: client.query(...).then is not a function
[2020-11-10T06:35:50.839Z] node_tests_1  |     at /app/test/instrumentation/modules/pg/pg.js:469:12
[2020-11-10T06:35:50.839Z] node_tests_1  |     at /app/node_modules/pg/lib/pool.js:84:11
[2020-11-10T06:35:50.839Z] node_tests_1  |     at elasticAPMCallbackWrapper (/app/lib/instrumentation/index.js:309:27)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at /app/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:347:9
[2020-11-10T06:35:50.839Z] node_tests_1  |     at /app/node_modules/pg/lib/pool.js:58:20
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:149:7)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Object.onceWrapper (events.js:286:20)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Connection.emit (events.js:203:15)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:12)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Socket.emit (events.js:198:13)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at addChunk (_stream_readable.js:288:12)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at readableAddChunk (_stream_readable.js:269:11)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at Socket.Readable.push (_stream_readable.js:224:10)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at TCP.onStreamRead [as _obOriginalOnread] (internal/stream_base_commons.js:94:17)
[2020-11-10T06:35:50.839Z] node_tests_1  |     at TCP.elasticAPMCallbackWrapper [as onread] (/app/lib/instrumentation/index.js:309:27)
[2020-11-10T06:35:50.839Z] node_tests_1  | -- detected failing command, flushing stdout...
[2020-11-10T06:35:50.839Z] node_tests_1  | TAP version 13
[2020-11-10T06:35:50.839Z] node_tests_1  | # handles promise rejections from pg
[2020-11-10T06:35:50.839Z] node_tests_1  | ok 1 null
[2020-11-10T06:35:50.839Z] node_tests_1  | 
[2020-11-10T06:35:50.839Z] node_tests_1  | -- fatal: Test exited with code 1
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! code ELIFECYCLE
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! errno 1
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! elastic-apm-node@3.8.0 test:tav: `tav --quiet`
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! Exit status 1
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! 
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! Failed at the elastic-apm-node@3.8.0 test:tav script.
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2020-11-10T06:35:50.839Z] node_tests_1  | 
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR! A complete log of this run can be found in:
[2020-11-10T06:35:50.839Z] node_tests_1  | npm ERR!     /tmp/.npm/_logs/2020-11-10T06_35_50_005Z-debug.log
```

I'm guessing this was caused by the recently merged elastic/apm-agent-nodejs#1846 
@astorm Are you able to take a look?

**Comment by astorm** [comment]
Possibly related to https://github.com/elastic/apm-agent-nodejs/pull/1846/files

**Comment by astorm** [comment]
```
% TAV=pg ./node_modules/.bin/tav --compat
Testing compatibility with pg:
✔ 8.5.0
✔ 8.4.2
✔ 8.4.1
✔ 8.4.0
✔ 8.3.3
✔ 8.3.2
✔ 8.3.0
✔ 8.2.2
✔ 8.2.1
✔ 8.2.0
✔ 8.1.0
✔ 8.0.3
✔ 8.0.2
✔ 8.0.1
✔ 8.0.0
✔ 7.18.2
✔ 7.18.1
✔ 7.18.0
✔ 7.17.1
✔ 7.17.0
✔ 7.16.1
✔ 7.16.0
✔ 7.15.2
✔ 7.15.1
✔ 7.15.0
✔ 7.14.0
✔ 7.13.0
✔ 7.12.1
✔ 7.12.0
✔ 7.11.0
✔ 7.10.0
✔ 7.9.0
✔ 7.8.2
✔ 7.8.1
✔ 7.8.0
✔ 7.7.1
✔ 7.7.0
✔ 7.6.1
✔ 7.6.0
✔ 7.5.0
✔ 7.4.3
✔ 7.4.2
✔ 7.4.1
✔ 7.4.0
✔ 7.3.0
✔ 7.2.0
✔ 7.1.2
✔ 7.0.3
✔ 7.1.1
✔ 6.4.2
✔ 6.3.3
✔ 6.2.5
✔ 6.1.6
✔ 6.0.5
✔ 5.2.1
✖ 4.5.7
✔ 7.1.0
✔ 7.0.2
✔ 7.0.1
✔ 7.0.0
✔ 6.4.1
✔ 6.4.0
✔ 6.3.1
✔ 6.3.0
✔ 6.2.4
✔ 6.2.3
✔ 6.2.2
✔ 6.1.5
✔ 6.1.4
✔ 6.1.3
✔ 6.1.2
✔ 6.1.1
✔ 6.1.0
✔ 6.0.4
✔ 6.0.3
✔ 6.0.2
✔ 6.0.1
✔ 6.0.0
✔ 5.1.0
✖ 5.0.0
✖ 4.5.6
✖ 4.5.5
✖ 4.5.4
✖ 4.5.3
✖ 4.5.2
✖ 4.5.1
✖ 4.5.0
✖ 4.4.6
✖ 4.4.5
✖ 4.4.4
✖ 4.4.3
✖ 4.4.2
✖ 4.4.1
✖ 4.4.0
✖ 4.3.0
✖ 4.2.0
✖ 4.1.1
✖ 4.1.0
✖ 4.0.0
```
