### ISSUE TITLE
Error while start agent 

### ISSUE THREAD

**Issue by victorbuttner** [elastic/apm-agent-nodejs#1926]
I`m getting this error while I start my application with agent configuration .

Agent.prototype.startTransaction = function (name, type, subtype, action, { startTime, childOf } = {}) {
                                                                          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/........./.../.../....../node_modules/elastic-apm-node/index.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by victorbuttner** [comment]
node version 4.
