### ISSUE TITLE
Error starting agent

### ISSUE THREAD

**Issue by victorbuttner** [elastic/apm-agent-nodejs#1927]
I`m getting this error while I start my application with agent configuration .

```
Agent.prototype.startTransaction = function (name, type, subtype, action, { startTime, childOf } = {}) {
^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/Users/........./.../.../....../node_modules/elastic-apm-node/index.js:3:13)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```

**Comment by astorm** [comment]
Hello @victorbuttner, thank you for reporting.  Do you know what version of Node.js you're running?

**Comment by victorbuttner** [comment]
Hello @astorm  I`m running it on node 4.9.1

**Comment by watson** [comment]
Hi @victorbuttner

Unfortunately Node.js version 4 isn't supported by the agent.

The 3.x version of agent supports Node.js v8.6.0 and newer, while the 2.x version of the agent supports Node.js 6.0.0 and newer.

You have to go all the way back to the 1.x version of the agent to have support for Node.js 4. But we do no longer support the 1.x range, so running that version would be at your own risk and would require an older version of the Elastic stack (v6.8) in order to function.

**Comment by victorbuttner** [comment]
thank you @watson .
