### ISSUE TITLE
TypeError: Cannot set property 'created_at' of undefined

### ISSUE THREAD

**Issue by htjuliantara** [elastic/apm-agent-nodejs#1966]
Versions:

node: 10.17.0
apm-agent-nodejs: 3.10.0
elasticsearch, apm-server: 7.9.2
the nodejs client throws (briefly after start when first sample is apparently processed) with

```
TypeError: Cannot set property 'created_at' of undefined
    at breadthFilter (/home/gateway/node_modules/breadth-filter/index.js:35:21)
    at Object.truncTransaction [as transaction] (/home/gateway/node_modules/elastic-apm-http-client/lib/truncate.js:107:18)
    at Client._encode (/home/gateway/node_modules/elastic-apm-http-client/index.js:333:34)
    at Client.encodeObject (/home/gateway/node_modules/elastic-apm-http-client/index.js:275:15)
    at Array.map (<anonymous>)
    at Client._writevCleaned (/home/gateway/node_modules/elastic-apm-http-client/index.js:279:22)
    at processBatch (/home/gateway/node_modules/elastic-apm-http-client/index.js:253:12)
    at Client._writev (/home/gateway/node_modules/elastic-apm-http-client/index.js:271:3)
    at doWrite (/home/gateway/node_modules/readable-stream/lib/_stream_writable.js:409:97)
    at clearBuffer (/home/gateway/node_modules/readable-stream/lib/_stream_writable.js:505:5)
    at Client.Writable.uncork (/home/gateway/node_modules/readable-stream/lib/_stream_writable.js:321:94)
    at Timeout._corkTimer.setTimeout [as _onTimeout] (/home/gateway/node_modules/elastic-apm-http-client/index.js:302:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
```

config:

```
ELASTIC_APM_SERVICE_NAME=xxx
ELASTIC_APM_SECRET_TOKEN=xxx
ELASTIC_APM_SERVER_URL=http://
ELASTIC_APM_VERIFY_SERVER_CERT=false
ELASTIC_APM_CAPTURE_BODY=all
```

gladly tell me what other information would be helpful :-)

**Comment by astorm** [comment]
@htjuliantara hello, nice to see you here.  First -- just as a heads up -- for general support questions your best bet it to hit up https://support.elastic.co/ -- the folks there will be better equipped to address specific usage problems.  Our GitHub issues are more for engineering related tasks around the agent.  We're always happy to hear about bugs here, but we're not equiped to provide the full level of support that https://support.elastic.co/ can.

> gladly tell me what other information would be helpful :-)

Ideally -- can you give us minimal steps to reproduce the problem?  We ask because we're not seeing the behavior you describe with our standard tests, so something specifically about your app or your use of the agent APIs is triggering this.

If it helps, based on the errors, it seems like your agent/app combination is something writing an undefined object where it should be writing a transaction.

**Comment by trentm** [comment]
Getting the output of a re-run with this change to your /home/gateway/node_modules/elastic-apm-http-client/lib/truncate.js might help point out an issue.

```diff
diff --git a/lib/truncate.js b/lib/truncate.js
index 0057277..72c2899 100644
--- a/lib/truncate.js
+++ b/lib/truncate.js
@@ -104,6 +104,7 @@ function truncMetadata (metadata, opts) {
 }

 function truncTransaction (trans, opts) {
+  console.warn('XXX truncTransaction', require('util').inspect(trans, false, 5))
   const result = breadthFilter(trans, {
     onArray,
     onObject: onObjectWithHeaders,
```

**Comment by htjuliantara** [comment]
thanks @trentm , I encountered an error when there was a custom header containing the json string, thats make target in breadth-filter undefined
so i set the config for capture header to false

**Comment by trentm** [comment]
@htjuliantara Thanks for getting back on this.

This is a bug we should fix in the APM agent. If you are able to give any detail on what that custom header was that caused the crash, we'd appreciate it to try to reproduce on our end.

**Comment by htjuliantara** [comment]
@trentm here the detail of trans:

so basically i make http request from a service that contains APM to another service
```XXX truncTransaction { id: 'ff15183fb2c679cd',
  trace_id: '8df7922ecdbc6abbe6fd9c0878be3733',
  parent_id: undefined,
  name: 'POST /api/v1/invoicer/*',
  type: 'request',
  subtype: null,
  action: null,
  duration: 347.314,
  timestamp: 1612757209447005,
  result: 'HTTP 2xx',
  sampled: true,
  context:
   { user: {},
     tags: {},
     custom: {},
     request:
      { http_version: '1.1',
        method: 'POST',
        url:
         { raw: '/some-route',
           protocol: 'https:',
           hostname: 'domain.com',
           port: '443',
           pathname: '/some-route',
           full:
            'https://domain.com/some-route' },
        socket: { remote_address: '::ffff:125.161.120.40', encrypted: true },
        headers:
         { host: 'domain.com',
           connection: 'keep-alive',
           'content-length': '91',
           accept: 'application/json, text/plain, */*',
           authorization: '[REDACTED]',
           'user-agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36',
           'content-type': 'application/json',
           origin: 'https://domain.com',
           'sec-fetch-site': 'same-site',
           'sec-fetch-mode': 'cors',
           'sec-fetch-dest': 'empty',
           referer: 'https://domain.com/',
           'accept-encoding': 'gzip, deflate, br',
           'accept-language': 'en-US,en;q=0.9',
           access_token: '[REDACTED]',
           user: '9cdf5c21-dfcb-43cb-be19-e7aa07f5f49a',
           user_data:
            User {
              created_at: 2020-05-26T06:39:05.000Z,
              updated_at: 2021-02-08T04:06:31.000Z,
              uuid: '9cdf5c21-dfcb-43cb-be19-e7aa07f5f49a',
              company_id: '4798187d-9c77-4928-8c12-06d341ef7934',
              name: 'Testing',
              phone: '08XXXXXXXXXX',
              email: 'email@gmail.com',
              emailVerified: true,
              password: '',
              remember_token: null,
              photo: null,
              is_creator: true,
              realm: null,
              username: null,
              verificationToken: null,
              has_onboarding: false,
              lastname: null,
              people_type: 'false',
              registered_by: '',
              plain_password: null,
              login_attempt: 0,
              login_limit_timestamp: null},
           company_data:
            Company {
              language_id: '1',
              created_at: 2020-05-26T06:39:05.000Z,
              updated_at: 2021-02-05T11:14:53.000Z,
              uuid: '4798187d-9c77-4928-8c12-06d341ef7934',
              company_name: ' Testing',
              company_phone: '08XXXXXXXXXX',
              company_email: 'email@gmail.com',
              company_contact: null,
              company_logo: null,
              company_website: 'www.domain.com',
              company_date_format: 'd/m/Y',
              company_bank_account: null,
              company_bank_name: null,
              company_favicon: null,
              company_subscription_type: null,
              company_type: 'pt',
              business_type_parent: 'Jasa',
              business_type_child: 'f89d843d-08c1-4b28-a597-a2003ef1ac3f',
              business_type_other: null,
              verification_token: null,
              email_verified: true,
              additional_user: 0 },
           subscription_data:
            Subscriptions {
              created_at: 2020-07-02T04:43:57.000Z,
              updated_at: 2020-07-02T04:43:57.000Z,
              uuid: 'e1fa213e-06b2-4fa6-8ad6-b624d10cefb4',
              company_id: '4798187d-9c77-4928-8c12-06d341ef7934',
              package_id: '4e6e53d0-ac29-11e8-a68a-a5e1fedf8ec0',
              start_date: 2020-07-01T21:43:58.000Z,
              end_date: 2021-07-02T04:43:58.000Z,
              amount: '1980000',
              affiliate_marketing_id: null,
              type_id: null,
              package:
               Packages {
                 created_at: 2018-08-30T07:50:04.000Z,
                 updated_at: 2018-08-30T07:50:04.000Z,
                 uuid: '4e6e53d0-ac29-11e8-a68a-a5e1fedf8ec0',
                 status: 'active',
                 package_type_id: '1c354023-3dc6-41fb-b13a-73d17454e76b'},
              status: 'active' } },
        body:
         '{"document_id":"d64e9cfb-c68d-4a67-8e27-73f6de6eea8d","document_type_id":"inv-03"}' },
     response:
      { status_code: 200,
        headers:
         { 'content-security-policy':
            'default-src \'self\';base-uri \'self\';block-all-mixed-content;font-src \'self\' https: data:;frame-ancestors \'self\';img-src \'self\' data:;object-src \'none\';script-src \'self\';script-src-attr \'none\';style-src \'self\' https: \'unsafe-inline\';upgrade-insecure-requests',
           'x-dns-prefetch-control': 'off',
           'expect-ct': 'max-age=0',
           'x-frame-options': 'SAMEORIGIN',
           'strict-transport-security': 'max-age=15552000; includeSubDomains',
           'x-download-options': 'noopen',
           'x-content-type-options': 'nosniff',
           'x-permitted-cross-domain-policies': 'none',
           'referrer-policy': 'no-referrer',
           'x-xss-protection': '0',
           'access-control-allow-origin': '*',
           'content-type': 'application/json; charset=utf-8',
           'content-length': '2701',
           etag: 'W/"a8d-+IQv9zr+k5CVHurCknmRMx36VrQ"',
           date: 'Mon, 08 Feb 2021 04:06:49 GMT',
           connection: 'keep-alive' } } },
  sync: false,
  span_count: { started: 6 },
  outcome: 'success' }```
