### ISSUE TITLE
Possible Timing Issues in  test/agent.js 

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2027]
We've noticed that tests in `test/agent.js` can fail in a race-condition-ish/timing sort of way, and we've been able to "fix" these failure by [upping the timer limits of callbacks that end certain requests/tests](https://github.com/elastic/apm-agent-nodejs/pull/2013/files#diff-893516fb8ebf3304a7e9b5e27c0cc116846898af68e9b1aa01f2a45fe66dc5d4R652).  It's unclear if these changes actually fix the test, or if the internet weather on the GHA virtual machines changed.  

Failure included below for posterity. 

```
not ok 241 plan != count
  ---
    operator: fail
    expected: 1
    actual:   0
    at: Timeout._onTimeout (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/agent.js:650:13)
    stack: |-
      Error: plan != count
          at Test.assert [as _assert] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:91:32)
          at completeEnd (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:243:18)
          at next (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:217:13)
          at Test._end (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:236:5)
          at Test.bound [as _end] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:91:32)
          at Test.end (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:191:10)
          at Test.bound [as end] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:91:32)
          at Timeout._onTimeout (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/agent.js:650:13)
          at ontimeout (timers.js:427:11)
          at tryOnTimeout (timers.js:289:5)
          at listOnTimeout (timers.js:252:5)
          at Timer.processTimers (timers.js:212:10)
```

Capturing a quote from @trentm 

> There are a number of setTimeout hacks in the test suite, some with comments like:

> `// Collecting the span stack trace is an async process. Wait a little before flushing`

> For this case we could consider using the callback to agent.captureError, so something like:

   ```
   agent.captureError(new Error('foo'), function () {
     server.close()
     t.end()
   })
   ```

**Comment by trentm** [comment]
This test has not been flaky for a long while now.
