### ISSUE TITLE
`Could not parse row {"span":{"name":"M�TY�!ype":"custom","id":"e8d827...` error in "Node.js-15-nightly*" jenkins tests

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2083]
We've had a few failures in a row of the "Node.js-15-nightly-no-async-hooks" and "Node.js-15-nightly"  jenkins tests that look like:

```
[2021-05-25T23:46:27.700Z] node_tests_1     | running (cwd: ./): node --unhandled-rejections=strict test/integration/skip-internal-http-spans.js
[2021-05-25T23:46:29.093Z] node_tests_1     | TAP version 13
[2021-05-25T23:46:29.093Z] node_tests_1     | # should not throw on socket close
[2021-05-25T23:46:29.093Z] node_tests_1     | node:events:304
[2021-05-25T23:46:29.093Z] node_tests_1     |       throw er; // Unhandled 'error' event
[2021-05-25T23:46:29.093Z] node_tests_1     |       ^
[2021-05-25T23:46:29.093Z] node_tests_1     |
[2021-05-25T23:46:29.093Z] node_tests_1     | Error: Could not parse row {"span":{"name":"���x�^UB�ype":"custom","id":"8484e...
[2021-05-25T23:46:29.093Z] node_tests_1     |     at DestroyableTransform.parseRow [as mapper] (/app/node_modules/ndjson/index.js:19:28)
[2021-05-25T23:46:29.093Z] node_tests_1     |     at DestroyableTransform.transform [as _transform] (/app/node_modules/split2/index.js:33:21)
...
```

Collected examples of that error line are:

```
[2021-05-25T23:45:32.420Z] node_tests_1     | Error: Could not parse row {"span":{"name":"M�TY�!ype":"custom","id":"e8d827...
[2021-05-25T23:46:29.093Z] node_tests_1     | Error: Could not parse row {"span":{"name":"���x�^UB�ype":"custom","id":"8484e...
[2021-05-26T08:42:55.340Z] node_tests_1     | Error: Could not parse row {"span":{"name":",2#k!})Iype":"custom","id":"2eee7...
[2021-05-26T08:42:10.362Z] node_tests_1     | Error: Could not parse row {"span":{"name":"�I����G�ype":"custom","id":"dde72...
.. Error: Could not parse row {"span":{"name":"\��o���ype":"custom","id":"164b8...
```

which show a pattern of corruption there.

The failing jenkins builds are:

- https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/905/
- https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/906/
- https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/907/

The error spot is consistent, so this isn't a fluke. I cannot repro via the following:

1. `.ci/scripts/test.sh "15" "" "true"` on my Mac
2. Running `node --unhandled-rejections=strict test/integration/skip-internal-http-spans.js` directly on macOS using the same ancient node v15 "nightly":

```
% node --version
v15.0.0-nightly2020102011f1ad939f
```

**Comment by trentm** [comment]
This corruption is consistently with the `span.name` value... but (again consistently) extending 8 bytes to the same spot in the serialized JSON.

```
{"span":{"name":"span","type":"custom",
                 ^^^^^^^^
{"span":{"name":",2#k!})Iype":"custom",
{"span":{"name":"�I����G�ype":"custom",
{"span":{"name":"���x�^UB�ype":"custom",
...
```

This suggests it is one of:
- a bug in `ndjson.serialize()` in the http-client during serialization, or
- a consistent bug in Gunzip or `ndjson.parse()` in the test code:

```js
    const server = http.createServer((req, res) => {
      req
        .pipe(zlib.createGunzip())
        .pipe(ndjson.parse())
        .on('data', data => {
          const key = Object.keys(data)[0]
          seen[key] = (seen[key] || 0) + 1
        })
        .on('end', () => res.end())
    })
```

But what changed that these are failing just now?
Build 903 (https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/903/) that passed used the same nightly v15.0.0 build:

```
[2021-05-24T08:32:42.814Z] node_tests_1     | v15.0.0-nightly2020102011f1ad939f
[2021-05-24T08:32:42.814Z] node_tests_1     | 7.0.2
```

**Comment by trentm** [comment]
Quicker (~25minutes) repro with https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/908/
which is from a build with these options:
![Screen Shot 2021-05-26 at 12 36 34 PM](https://user-images.githubusercontent.com/46866/119720627-10336780-be1f-11eb-8772-0c1c4fbeb8dd.png)

**Comment by trentm** [comment]
Using this diff:

```js
diff --git a/test/integration/skip-internal-http-spans.js b/test/integration/skip-internal-http-spans.js
index 6e3dd13..1af3a21 100644
--- a/test/integration/skip-internal-http-spans.js
+++ b/test/integration/skip-internal-http-spans.js
@@ -1,5 +1,6 @@
 'use strict'

+const { Transform } = require('stream')
 const getPort = require('get-port')

 const agent = require('../../')
@@ -13,6 +14,15 @@ getPort().then(port => {
     centralConfig: false
   })

+  // XXX
+  // Client.prototype._encode = function (obj, enc) {
+  agent._transport._origEncode = agent._transport._encode
+  agent._transport._encode = function (obj, enc) {
+    const encoded = this._origEncode(obj, enc)
+    console.warn('XXX encoded: %s', encoded)
+    return encoded
+  }
+
   // hack to ensure that all incoming http requests picked up on the mock APM
   // Server doesn't generate any transactions that again will be sent to the
   // same APM Server
@@ -43,6 +53,13 @@ getPort().then(port => {
     const server = http.createServer((req, res) => {
       req
         .pipe(zlib.createGunzip())
+        .pipe(new Transform({
+          transform (chunk, encoding, callback) {
+            console.warn('XXX gunzipped+toStringed chunk:', chunk.toString())
+            this.push(chunk)
+            callback()
+          }
+        }))
         .pipe(ndjson.parse())
         .on('data', data => {
           const key = Object.keys(data)[0]
```

and getting this result:

```
13:35:34  node_tests_1     | running (cwd: ./): node --unhandled-rejections=strict test/integration/skip-internal-http-spans.js
13:35:35  node_tests_1     | TAP version 13
13:35:35  node_tests_1     | # should not throw on socket close
13:35:35  node_tests_1     | XXX encoded: {"metadata":{"service":{"name":"test","environment":"development","runtime":{"name":"node","version":"15.0.0-nightly2020102011f1ad939f"},"language":{"name":"javascript"},"agent":{"name":"nodejs","version":"3.15.0"},"version":"3.15.0"},"process":{"pid":123,"ppid":57,"title":"node","argv":["/usr/local/nvm/versions/node/v15.0.0-nightly2020102011f1ad939f/bin/node","/app/test/integration/skip-internal-http-spans.js"]},"system":{"hostname":"5f558fa363ea","architecture":"x64","platform":"linux","container":{"id":"5f558fa363ea1069f44e45dad39a37d5d24dc4175be5af638eb6b345114cae9c"}},"cloud":{"availability_zone":"us-central1-f","region":"us-central1","instance":{"id":"2594217265662726700"},"machine":{"type":"n1-standard-4"},"provider":"gcp","project":{"id":"543704608146","name":"elastic-ci-prod"}}}}
13:35:35  node_tests_1     | 
13:35:35  node_tests_1     | XXX encoded: {"span":{"name":"span","type":"custom","id":"f6a54257ec22f793","transaction_id":"f6a54257ec22f793","parent_id":"f6a54257ec22f793","trace_id":"0097a2fbdd10a0b7985f265b13a046bf","subtype":null,"action":null,"timestamp":1622061335364721,"duration":3.416,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":73,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
13:35:35  node_tests_1     | 
13:35:35  node_tests_1     | XXX gunzipped+toStringed chunk: {"metadata":{"service":{"name":"test","environment":"development","runtime":{"name":"node","version":"15.0.0-nightly2020102011f1ad939f"},"language":{"name":"javascript"},"agent":{"name":"nodejs","version":"3.15.0"},"version":"3.15.0"},"process":{"pid":123,"ppid":57,"title":"node","argv":["/usr/local/nvm/versions/node/v15.0.0-nightly2020102011f1ad939f/bin/node","/app/test/integration/skip-internal-http-spans.js"]},"system":{"hostname":"5f558fa363ea","architecture":"x64","platform":"linux","container":{"id":"5f558fa363ea1069f44e45dad39a37d5d24dc4175be5af638eb6b345114cae9c"}},"cloud":{"availability_zone":"us-central1-f","region":"us-central1","instance":{"id":"2594217265662726700"},"machine":{"type":"n1-standard-4"},"provider":"gcp","project":{"id":"543704608146","name":"elastic-ci-prod"}}}}
13:35:35  node_tests_1     | {"span":{"name":"Շ�wp)I�ype":"custom","id":"f6a54257ec22f793","transaction_id":"f6a54257ec22f793","parent_id":"f6a54257ec22f793","trace_id":"0097a2fbdd10a0b7985f265b13a046bf","subtype":null,"action":null,"timestamp":1622061335364721,"duration":3.416,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":73,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
13:35:35  node_tests_1     | 
13:35:35  node_tests_1     | node:events:304
13:35:35  node_tests_1     |       throw er; // Unhandled 'error' event
13:35:35  node_tests_1     |       ^
13:35:35  node_tests_1     | 
13:35:35  node_tests_1     | Error: Could not parse row {"span":{"name":"Շ�wp)I�ype":"custom","id":"f6a542...
13:35:35  node_tests_1     |     at DestroyableTransform.parseRow [as mapper] (/app/node_modules/ndjson/index.js:19:28)
```

Suggests a problem with Gzip/Gunzip or with transport.

**Comment by trentm** [comment]
dumping the received raw gzipped chunks:

```
14:20:14  node_tests_1     | TAP version 13
14:20:14  node_tests_1     | # should not throw on socket close
14:20:14  node_tests_1     | XXX encoded: {"metadata":{"service":{"name":"test","environment":"development","runtime":{"name":"node","version":"15.0.0-nightly2020102011f1ad939f"},"language":{"name":"javascript"},"agent":{"name":"nodejs","version":"3.15.0"},"version":"3.15.0"},"process":{"pid":214,"ppid":148,"title":"node","argv":["/usr/local/nvm/versions/node/v15.0.0-nightly2020102011f1ad939f/bin/node","/app/test/integration/skip-internal-http-spans.js"]},"system":{"hostname":"3c6ac7207db9","architecture":"x64","platform":"linux","container":{"id":"3c6ac7207db90829b18c2fa43f9d7ea5d54020618a74cdc0d7383fab645f8db5"}},"cloud":{"availability_zone":"us-central1-b","region":"us-central1","instance":{"id":"7364961075705611000"},"machine":{"type":"n1-standard-4"},"provider":"gcp","project":{"id":"543704608146","name":"elastic-ci-prod"}}}}
14:20:14  node_tests_1     | 
14:20:14  node_tests_1     | XXX encoded: {"span":{"name":"span","type":"custom","id":"dc54e011c66bed1d","transaction_id":"dc54e011c66bed1d","parent_id":"dc54e011c66bed1d","trace_id":"ab113bdc29c860e4d62063c8c7912e4a","subtype":null,"action":null,"timestamp":1622064014110670,"duration":4.359,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":80,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
14:20:14  node_tests_1     | 
14:20:14  node_tests_1     | XXX raw chunk (base64): H4sIAAAAAAAAAw==
14:20:14  node_tests_1     | XXX raw chunk (base64): rVbdjuM0FL7nMXzdNHHiJE2FkEZcIQFC7EhcoFV1YjutZxwn2E6ZMuozIB5lr3klngFxnHaHpNthZ5a9qJocn3O+7/w6j6SVHgR4IOtH4qTdKy7Do4EW/4mXzpMFkWavbGdaaTwKhdxL3fXj24LYwXjVTo1MJyQe7KV1qjMooPkyWSaRUdud14c0SRMafrShIKqsashxQTSY7QDbqZ872IPjVvU+KOBZQJ+h3LkZTrYMSEH5mqy3HZfOBRe9EmSdUobC8ZGy1YJ45fWEPtjtnqx/JvHgbKw7Djo2+zY+e3ZxUIv3HwstrpWJzx5j6Ps4ZDRWxsutBY+OYnev+igIrAEd7bzvI9eDcUsM7i3SdgfnZRtY7zrnz8FnvABepkkp6mrkynfKS+4HG04fCobCXoNvOoumRCszPKCId8aDMtIGdyHwmaNklVY1XfG0AZY1lSgl5CJnGE9BV1AyLngiymyVNVAXLG9Wos7JESly3Q0iuMSCKQ210sofNr91JpAZXMSxchY0jerQL3J7qszkAMXKOA/m1HwjszIrWFXQpMzLJC8oTZKxii1gqGZU84d+rBeNgqkAKyJ2LvReiRAk2fKejII7TM6T65xlZcKKZEVZgcfnnEoNzisecRWhgcDIjscvcCiwGJO2e/fr33/8+dfv9oTNB+e7NtAPfgXPmcTi86KopaAC5RieccBDpTfP6fRgMQ/PHqMLLk+nUFOa1YKnFV8ViWSiwNpkfMXLiqaSAWq7oT7lxQxaY2eM0O/fwqBirtoeW75I0ZYllGFqizJZEDGcOpKs2TLLK3Tlgd+P6DgHj6RRWp6ToFUdh4LZISyBUx9PIl2Oc4lNJ01H1sWCNIM58yC3EzUEsP5NyG/Qri3Yw6axI0QD2kmkX7tND36HhuP0vAD4uPgoVWWEfJiTpHTG8pu5xWdi+oR7heO43i44zTN3M2p8GpMn7xfIr9pG/zJbJTNmb/DekHb5JZjOHNpucF+9mNyrCFyQD2t1jXeR8VNuLMtm5DpcKj9ZxMKF8AErLM+c1NTni+CytJzByVb5/4dzrXNOedjhohDzSuTXCnGdwysa9QLuWiKM9NNWzdLkgzR8q/DmMspsv799aUaC108bYHaBf1rmNz989zVoXeMie7YHPsMAj9zfN218/tCIPbj7zS+DHOSUaFnNiJ6VbxW/dzdG/CjDTRU+MF6asv+EPb4NHxCGP0XZDZ53I2c38PFzCBXwQtBygwOIcoqX3j9IuJFiFgoAAA==
14:20:14  node_tests_1     | XXX gunzipped+toStringed chunk: {"metadata":{"service":{"name":"test","environment":"development","runtime":{"name":"node","version":"15.0.0-nightly2020102011f1ad939f"},"language":{"name":"javascript"},"agent":{"name":"nodejs","version":"3.15.0"},"version":"3.15.0"},"process":{"pid":214,"ppid":148,"title":"node","argv":["/usr/local/nvm/versions/node/v15.0.0-nightly2020102011f1ad939f/bin/node","/app/test/integration/skip-internal-http-spans.js"]},"system":{"hostname":"3c6ac7207db9","architecture":"x64","platform":"linux","container":{"id":"3c6ac7207db90829b18c2fa43f9d7ea5d54020618a74cdc0d7383fab645f8db5"}},"cloud":{"availability_zone":"us-central1-b","region":"us-central1","instance":{"id":"7364961075705611000"},"machine":{"type":"n1-standard-4"},"provider":"gcp","project":{"id":"543704608146","name":"elastic-ci-prod"}}}}
14:20:14  node_tests_1     | {"span":{"name":"�w����rype":"custom","id":"dc54e011c66bed1d","transaction_id":"dc54e011c66bed1d","parent_id":"dc54e011c66bed1d","trace_id":"ab113bdc29c860e4d62063c8c7912e4a","subtype":null,"action":null,"timestamp":1622064014110670,"duration":4.359,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":80,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
14:20:14  node_tests_1     | 
14:20:14  node_tests_1     | node:events:304
14:20:14  node_tests_1     |       throw er; // Unhandled 'error' event
14:20:14  node_tests_1     |       ^
14:20:14  node_tests_1     | 
14:20:14  node_tests_1     | Error: Could not parse row {"span":{"name":"�w����rype":"custom","id":"dc54e0...
14:20:14  node_tests_1     |     at DestroyableTransform.parseRow [as mapper] (/app/node_modules/ndjson/index.js:19:28)
```


and re-creating the gz content:

```python
s1 = 'H4sIAAAAAAAAAw=='
s2 = 'rVbdjuM0FL7nMXzdNHHiJE2FkEZcIQFC7EhcoFV1YjutZxwn2E6ZMuozIB5lr3klngFxnHaHpNthZ5a9qJocn3O+7/w6j6SVHgR4IOtH4qTdKy7Do4EW/4mXzpMFkWavbGdaaTwKhdxL3fXj24LYwXjVTo1MJyQe7KV1qjMooPkyWSaRUdud14c0SRMafrShIKqsashxQTSY7QDbqZ872IPjVvU+KOBZQJ+h3LkZTrYMSEH5mqy3HZfOBRe9EmSdUobC8ZGy1YJ45fWEPtjtnqx/JvHgbKw7Djo2+zY+e3ZxUIv3HwstrpWJzx5j6Ps4ZDRWxsutBY+OYnev+igIrAEd7bzvI9eDcUsM7i3SdgfnZRtY7zrnz8FnvABepkkp6mrkynfKS+4HG04fCobCXoNvOoumRCszPKCId8aDMtIGdyHwmaNklVY1XfG0AZY1lSgl5CJnGE9BV1AyLngiymyVNVAXLG9Wos7JESly3Q0iuMSCKQ210sofNr91JpAZXMSxchY0jerQL3J7qszkAMXKOA/m1HwjszIrWFXQpMzLJC8oTZKxii1gqGZU84d+rBeNgqkAKyJ2LvReiRAk2fKejII7TM6T65xlZcKKZEVZgcfnnEoNzisecRWhgcDIjscvcCiwGJO2e/fr33/8+dfv9oTNB+e7NtAPfgXPmcTi86KopaAC5RieccBDpTfP6fRgMQ/PHqMLLk+nUFOa1YKnFV8ViWSiwNpkfMXLiqaSAWq7oT7lxQxaY2eM0O/fwqBirtoeW75I0ZYllGFqizJZEDGcOpKs2TLLK3Tlgd+P6DgHj6RRWp6ToFUdh4LZISyBUx9PIl2Oc4lNJ01H1sWCNIM58yC3EzUEsP5NyG/Qri3Yw6axI0QD2kmkX7tND36HhuP0vAD4uPgoVWWEfJiTpHTG8pu5xWdi+oR7heO43i44zTN3M2p8GpMn7xfIr9pG/zJbJTNmb/DekHb5JZjOHNpucF+9mNyrCFyQD2t1jXeR8VNuLMtm5DpcKj9ZxMKF8AErLM+c1NTni+CytJzByVb5/4dzrXNOedjhohDzSuTXCnGdwysa9QLuWiKM9NNWzdLkgzR8q/DmMspsv799aUaC108bYHaBf1rmNz989zVoXeMie7YHPsMAj9zfN218/tCIPbj7zS+DHOSUaFnNiJ6VbxW/dzdG/CjDTRU+MF6asv+EPb4NHxCGP0XZDZ53I2c38PFzCBXwQtBygwOIcoqX3j9IuJFiFgoAAA=='
b1 = s1.decode('base64')
b2 = s2.decode('base64')
f = open('foo.gz', 'wb')
f.write(b1)
f.write(b2)
f.close()
```

and:

```
% gunzip foo.gz
% cat foo
{"metadata":{"service":{"name":"test","environment":"development","runtime":{"name":"node","version":"15.0.0-nightly2020102011f1ad939f"},"language":{"name":"javascript"},"agent":{"name":"nodejs","version":"3.15.0"},"version":"3.15.0"},"process":{"pid":214,"ppid":148,"title":"node","argv":["/usr/local/nvm/versions/node/v15.0.0-nightly2020102011f1ad939f/bin/node","/app/test/integration/skip-internal-http-spans.js"]},"system":{"hostname":"3c6ac7207db9","architecture":"x64","platform":"linux","container":{"id":"3c6ac7207db90829b18c2fa43f9d7ea5d54020618a74cdc0d7383fab645f8db5"}},"cloud":{"availability_zone":"us-central1-b","region":"us-central1","instance":{"id":"7364961075705611000"},"machine":{"type":"n1-standard-4"},"provider":"gcp","project":{"id":"543704608146","name":"elastic-ci-prod"}}}}
{"span":{"name":"�w����rype":"custom","id":"dc54e011c66bed1d","transaction_id":"dc54e011c66bed1d","parent_id":"dc54e011c66bed1d","trace_id":"ab113bdc29c860e4d62063c8c7912e4a","subtype":null,"action":null,"timestamp":1622064014110670,"duration":4.359,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":80,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
```

IOW, the problem is on the sending side. Guessing that gzipping in elastic-apm-client has a bug in this case.

**Comment by trentm** [comment]
I hacked in a static span object to send to apm-server and the result:

```
16:12:33  node_tests_1     | {"walla":"walla",DZlƸ���"name":"SPAN","type":"custom","id":"123fbe88aade951d","transaction_id":"123fbe88aade951d","parent_id":"123fbe88aade951d","trace_id":"690916c68c76b27b15922a9730d06644","subtype":null,"action":null,"timestamp":1622067538909570,"duration":2.857,"stacktrace":[{"filename":"lib/instrumentation/transaction.js","lineno":6,"function":"Transaction.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/transaction.js"},{"filename":"lib/instrumentation/index.js","lineno":11,"function":"Instrumentation.startSpan","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"lib/agent.js","lineno":16,"function":"Agent.startSpan","library_frame":false,"abs_path":"/app/lib/agent.js"},{"filename":"test/integration/skip-internal-http-spans.js","lineno":81,"function":"Server.<anonymous>","library_frame":false,"abs_path":"/app/test/integration/skip-internal-http-spans.js"},{"filename":"node:events","lineno":433,"function":"onceWrapper","library_frame":true,"abs_path":"node:events"},{"filename":"node:events","lineno":327,"function":"emit","library_frame":true,"abs_path":"node:events"},{"filename":"lib/instrumentation/http-shared.js","lineno":5,"function":"Server.emit","library_frame":false,"abs_path":"/app/lib/instrumentation/http-shared.js"},{"filename":"node:net","lineno":1320,"function":"emitListeningNT","library_frame":true,"abs_path":"node:net"},{"filename":"lib/instrumentation/index.js","lineno":40,"function":"elasticAPMCallbackWrapper","library_frame":false,"abs_path":"/app/lib/instrumentation/index.js"},{"filename":"node:internal/process/task_queues","lineno":79,"function":"processTicksAndRejections","library_frame":true,"abs_path":"node:internal/process/task_queues"}],"sync":false,"outcome":"success","sample_rate":1}}
```

shows that the corruption isn't about the `span.name` (that was a fluke) but starts at 18 bytes into the payload.

I was unable to reproduce this corruption with manual play in `% docker run --rm -ti ubuntu:18.04 /bin/sh` -- which is my poorman's guess at the env of the jenkins builder containers from gobld -- and using the same nightly-node v15.0.0 build.

**Comment by trentm** [comment]
This is worked around by https://github.com/elastic/apm-agent-nodejs/pull/2087 which drops testing of Node.js v15 nightly builds in favour of Node.js v17 nightly builds. I don't fully grok the failure mode, which is unsatisfying, but this isn't worth chasing.
