### ISSUE TITLE
Jenkins: Inconsistant Results in Cassandra, IO Redis, and HTTP Disabled Tests

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2089]
**Describe the bug**

We've been seeing the Jenkins PR tests occasionally flake out tests (seemingly?) unrelated to the code that's under test -- rerunning the tests clears these problems up.  

This issue is for tracking/archiving this behavior over time to see if we can determine which tests seem to be affected so we can determine if this is a problem with the tests, a problem with the agent, or a problem with the testing environment.  

Current know places tests flake out are in:
```
FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:221:5
FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:224:5
FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:228:5
FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:231:5
FAILED AT: /app/test/instrumentation/modules/http/disabling.js:48:9
FAILED AT: /app/test/instrumentation/modules/http/disabling.js:75:9
FAILED AT: /app/test/instrumentation/modules/ioredis.js:155:9
FAILED AT: C:\Users\jenkins\workspace\ejs_apm-agent-nodejs-mbp_PR-2081\src\github.com\elastic\apm-agent-nodejs\test\instrumentation\modules\ioredis.js:155:9
```

The failures all appear to center around expected spans missing from the test results.

Below are some excerpts from the logs -- see [failures.zip](https://github.com/elastic/apm-agent-nodejs/files/6556135/failures.zip) for a full list. 

```
    not ok 43 span name
    [2021-05-26T17:28:54.085Z] node_tests_1     |   ---
    [2021-05-26T17:28:54.085Z] node_tests_1     |     operator: equal
    [2021-05-26T17:28:54.085Z] node_tests_1     |     expected: |-
    [2021-05-26T17:28:54.085Z] node_tests_1     |       'Cassandra: Connect'
    [2021-05-26T17:28:54.085Z] node_tests_1     |     actual: |-
    [2021-05-26T17:28:54.085Z] node_tests_1     |       'Cassandra: Batch query'
    [2021-05-26T17:28:54.085Z] node_tests_1     |     at: assertConnectSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:221:5)
    [2021-05-26T17:28:54.085Z] node_tests_1     |     stack: |-
    [2021-05-26T17:28:54.085Z] node_tests_1     |       Error: span name
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at assertConnectSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:221:5)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at /app/test/instrumentation/modules/cassandra-driver/index.js:90:7
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Object._write (/app/test/_mock_http_client.js:40:50)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at Object.sendSpan (/app/test/_mock_http_client.js:44:12)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at /app/lib/instrumentation/index.js:11:7997
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at done (/app/lib/instrumentation/span.js:11:1065)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at _stackObj.then.value (/app/lib/instrumentation/span.js:10:1737)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at value.get.value (/app/node_modules/async-value-promise/index.js:30:27)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at AsyncValue.set (/app/node_modules/async-value/index.js:30:7)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at AsyncValuePromise.resolve (/app/node_modules/async-value-promise/index.js:60:18)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at afterAll (/app/lib/instrumentation/span.js:6:717)
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at /app/node_modules/after-all-results/index.js:20:25
    [2021-05-26T17:28:54.085Z] node_tests_1     |           at process._tickCallback (internal/process/next_tick.js:61:11)
    [2021-05-26T17:28:54.085Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:221:5

    not ok 46 span action
    [2021-05-26T17:28:54.085Z] node_tests_1     |   ---
    [2021-05-26T17:28:54.085Z] node_tests_1     |     operator: equal
    [2021-05-26T17:28:54.085Z] node_tests_1     |     expected: 'connect'
    [2021-05-26T17:28:54.085Z] node_tests_1     |     actual:   'query'
    [2021-05-26T17:28:54.085Z] node_tests_1     |     at: assertConnectSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:224:5)
    [2021-05-26T17:28:54.085Z] node_tests_1     |     stack: |-
    [2021-05-26T17:28:54.085Z] node_tests_1     |       Error: span action
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at assertConnectSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:224:5)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/test/instrumentation/modules/cassandra-driver/index.js:90:7
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object._write (/app/test/_mock_http_client.js:40:50)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object.sendSpan (/app/test/_mock_http_client.js:44:12)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/lib/instrumentation/index.js:11:7997
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at done (/app/lib/instrumentation/span.js:11:1065)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at _stackObj.then.value (/app/lib/instrumentation/span.js:10:1737)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at value.get.value (/app/node_modules/async-value-promise/index.js:30:27)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValue.set (/app/node_modules/async-value/index.js:30:7)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValuePromise.resolve (/app/node_modules/async-value-promise/index.js:60:18)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at afterAll (/app/lib/instrumentation/span.js:6:717)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/node_modules/after-all-results/index.js:20:25
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at process._tickCallback (internal/process/next_tick.js:61:11)
    [2021-05-26T17:28:54.086Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:224:5    
    
    not ok 47 span name
    [2021-05-26T17:28:54.086Z] node_tests_1     |   ---
    [2021-05-26T17:28:54.086Z] node_tests_1     |     operator: equal
    [2021-05-26T17:28:54.086Z] node_tests_1     |     expected: |-
    [2021-05-26T17:28:54.086Z] node_tests_1     |       'Cassandra: Batch query'
    [2021-05-26T17:28:54.086Z] node_tests_1     |     actual: |-
    [2021-05-26T17:28:54.086Z] node_tests_1     |       'Cassandra: Connect'
    [2021-05-26T17:28:54.086Z] node_tests_1     |     at: assertSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:228:5)
    [2021-05-26T17:28:54.086Z] node_tests_1     |     stack: |-
    [2021-05-26T17:28:54.086Z] node_tests_1     |       Error: span name
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at assertSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:228:5)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/test/instrumentation/modules/cassandra-driver/index.js:92:7
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object._write (/app/test/_mock_http_client.js:40:50)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object.sendSpan (/app/test/_mock_http_client.js:44:12)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/lib/instrumentation/index.js:11:7997
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at done (/app/lib/instrumentation/span.js:11:1065)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at _stackObj.then.value (/app/lib/instrumentation/span.js:10:1737)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at value.get.value (/app/node_modules/async-value-promise/index.js:30:27)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValue.set (/app/node_modules/async-value/index.js:30:7)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValuePromise.resolve (/app/node_modules/async-value-promise/index.js:60:18)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at afterAll (/app/lib/instrumentation/span.js:6:717)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/node_modules/after-all-results/index.js:20:25
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at process._tickCallback (internal/process/next_tick.js:61:11)
    [2021-05-26T17:28:54.086Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:228:5   
    
    not ok 50 span action
    [2021-05-26T17:28:54.086Z] node_tests_1     |   ---
    [2021-05-26T17:28:54.086Z] node_tests_1     |     operator: equal
    [2021-05-26T17:28:54.086Z] node_tests_1     |     expected: 'query'
    [2021-05-26T17:28:54.086Z] node_tests_1     |     actual:   'connect'
    [2021-05-26T17:28:54.086Z] node_tests_1     |     at: assertSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:231:5)
    [2021-05-26T17:28:54.086Z] node_tests_1     |     stack: |-
    [2021-05-26T17:28:54.086Z] node_tests_1     |       Error: span action
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at assertSpan (/app/test/instrumentation/modules/cassandra-driver/index.js:231:5)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/test/instrumentation/modules/cassandra-driver/index.js:92:7
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object._write (/app/test/_mock_http_client.js:40:50)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at Object.sendSpan (/app/test/_mock_http_client.js:44:12)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/lib/instrumentation/index.js:11:7997
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at done (/app/lib/instrumentation/span.js:11:1065)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at _stackObj.then.value (/app/lib/instrumentation/span.js:10:1737)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at value.get.value (/app/node_modules/async-value-promise/index.js:30:27)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValue.set (/app/node_modules/async-value/index.js:30:7)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at AsyncValuePromise.resolve (/app/node_modules/async-value-promise/index.js:60:18)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at afterAll (/app/lib/instrumentation/span.js:6:717)
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at /app/node_modules/after-all-results/index.js:20:25
    [2021-05-26T17:28:54.086Z] node_tests_1     |           at process._tickCallback (internal/process/next_tick.js:61:11)
    [2021-05-26T17:28:54.086Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/cassandra-driver/index.js:231:5     
    
    not ok 22 span count
    [2021-05-26T17:51:16.168Z] node_tests_1     |   ---
    [2021-05-26T17:51:16.168Z] node_tests_1     |     operator: equal
    [2021-05-26T17:51:16.168Z] node_tests_1     |     expected: 1
    [2021-05-26T17:51:16.168Z] node_tests_1     |     actual:   0
    [2021-05-26T17:51:16.168Z] node_tests_1     |     at: t.test.makeTest (/app/test/instrumentation/modules/http/disabling.js:75:9)
    [2021-05-26T17:51:16.168Z] node_tests_1     |     stack: |-
    [2021-05-26T17:51:16.168Z] node_tests_1     |       Error: span count
    [2021-05-26T17:51:16.168Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:51:16.168Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:51:16.168Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:51:16.168Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at t.test.makeTest (/app/test/instrumentation/modules/http/disabling.js:75:9)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at Worker.worker.on.data (/app/test/instrumentation/modules/http/disabling.js:17:11)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at Worker.emit (events.js:203:15)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at ChildProcess.emit (events.js:198:13)
    [2021-05-26T17:51:16.169Z] node_tests_1     |           at emit (internal/child_process.js:832:12)
    [2021-05-26T17:51:16.169Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/http/disabling.js:75:9
    
    From: https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2081/17/consoleFull
    ```
    not ok 22 span count
    [2021-05-26T17:26:17.530Z] node_tests_1     |   ---
    [2021-05-26T17:26:17.530Z] node_tests_1     |     operator: equal
    [2021-05-26T17:26:17.530Z] node_tests_1     |     expected: 1
    [2021-05-26T17:26:17.530Z] node_tests_1     |     actual:   0
    [2021-05-26T17:26:17.530Z] node_tests_1     |     at: <anonymous> (/app/test/instrumentation/modules/http/disabling.js:75:9)
    [2021-05-26T17:26:17.530Z] node_tests_1     |     stack: |-
    [2021-05-26T17:26:17.530Z] node_tests_1     |       Error: span count
    [2021-05-26T17:26:17.530Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at /app/test/instrumentation/modules/http/disabling.js:75:9
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at Worker.<anonymous> (/app/test/instrumentation/modules/http/disabling.js:17:11)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at Worker.emit (node:events:377:35)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at ChildProcess.<anonymous> (node:internal/cluster/worker:33:12)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at ChildProcess.emit (node:events:365:28)
    [2021-05-26T17:26:17.531Z] node_tests_1     |           at emit (node:internal/child_process:920:12)
    [2021-05-26T17:26:17.531Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/http/disabling.js:75:9    
    
    not ok 71 should be strictly equal
    [2021-05-26T17:48:28.014Z] node_tests_1     |   ---
    [2021-05-26T17:48:28.014Z] node_tests_1     |     operator: equal
    [2021-05-26T17:48:28.014Z] node_tests_1     |     expected: 'GET'
    [2021-05-26T17:48:28.014Z] node_tests_1     |     actual:   'SADD'
    [2021-05-26T17:48:28.014Z] node_tests_1     |     at: <anonymous> (/app/test/instrumentation/modules/ioredis.js:155:9)
    [2021-05-26T17:48:28.014Z] node_tests_1     |     stack: |-
    [2021-05-26T17:48:28.014Z] node_tests_1     |       Error: should be strictly equal
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:304:54)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Test.bound [as _assert] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:468:10)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Test.bound [as strictEqual] (/app/node_modules/tape/lib/test.js:91:32)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/test/instrumentation/modules/ioredis.js:155:9
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Array.forEach (<anonymous>)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/test/instrumentation/modules/ioredis.js:153:12
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Object._write (/app/test/_mock_http_client.js:40:50)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at Object.sendSpan (/app/test/_mock_http_client.js:44:12)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/lib/instrumentation/index.js:11:7997
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at done (/app/lib/instrumentation/span.js:11:1065)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/lib/instrumentation/span.js:10:1737
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/node_modules/async-value-promise/index.js:30:27
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at AsyncValue.set (/app/node_modules/async-value/index.js:30:7)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at AsyncValuePromise.resolve (/app/node_modules/async-value-promise/index.js:60:18)
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/lib/instrumentation/span.js:6:717
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at /app/node_modules/after-all-results/index.js:20:25
    [2021-05-26T17:48:28.014Z] node_tests_1     |           at processTicksAndRejections (internal/process/task_queues.js:79:11)
    [2021-05-26T17:48:28.014Z] node_tests_1     |   ...
    FAILED AT: /app/test/instrumentation/modules/ioredis.js:155:9    
```

**Comment by astorm** [comment]
Possibly related to https://github.com/elastic/apm-agent-nodejs/pull/2081

**Comment by trentm** [comment]
I haven't seen any of these in ages. I'm assuming they are fixed.
