### ISSUE TITLE
benchmarks in CI occasionally fail with "Error: listen EADDRINUSE: address already in use :::8200"

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2131]
Benchmark runs in CI occasionally fail with "Error: listen EADDRINUSE: address already in use :::8200".
For example:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/948/pipeline

```
...
[2021-06-24T23:39:15.367Z] + benchmarks=($basedir/0*.js)
[2021-06-24T23:39:15.367Z] + for benchmark in '"${benchmarks[@]}"'
[2021-06-24T23:39:15.367Z] + runBenchmark ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js
[2021-06-24T23:39:15.367Z] + benchmark=././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js
[2021-06-24T23:39:15.367Z] + sleep 1
[2021-06-24T23:39:16.816Z] + log 'Running benchmark ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js without agent...'
[2021-06-24T23:39:16.816Z] + msg='Running benchmark ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js without agent...'
[2021-06-24T23:39:16.816Z] + '[' '!' -z '' ']'
[2021-06-24T23:39:16.816Z] + node ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js
[2021-06-24T23:40:22.754Z] + startAPMServer
[2021-06-24T23:40:22.754Z] + log 'Starting mock APM Server...'
[2021-06-24T23:40:22.754Z] + msg='Starting mock APM Server...'
[2021-06-24T23:40:22.754Z] + '[' '!' -z '' ']'
[2021-06-24T23:40:22.754Z] + pid=2851137
[2021-06-24T23:40:22.754Z] + log 'Mock APM Server running as pid 2851137'
[2021-06-24T23:40:22.754Z] + msg='Mock APM Server running as pid 2851137'
[2021-06-24T23:40:22.754Z] + '[' '!' -z '' ']'
[2021-06-24T23:40:22.754Z] + sleep 1
[2021-06-24T23:40:22.754Z] + node ././test/benchmarks/scripts/../utils/apm-server.js
[2021-06-24T23:40:22.754Z] events.js:352
[2021-06-24T23:40:22.754Z]       throw er; // Unhandled 'error' event
[2021-06-24T23:40:22.754Z]       ^
[2021-06-24T23:40:22.754Z] 
[2021-06-24T23:40:22.754Z] Error: listen EADDRINUSE: address already in use :::8200
[2021-06-24T23:40:22.754Z]     at Server.setupListenHandle [as _listen2] (net.js:1320:16)
[2021-06-24T23:40:22.754Z]     at listenInCluster (net.js:1368:12)
[2021-06-24T23:40:22.754Z]     at Server.listen (net.js:1454:7)
[2021-06-24T23:40:22.754Z]     at Object.<anonymous> (/var/lib/jenkins/workspace/dejs_apm-agent-nodejs-mbp_master/948/src/github.com/elastic/apm-agent-nodejs/test/benchmarks/utils/apm-server.js:16:8)
[2021-06-24T23:40:22.754Z]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[2021-06-24T23:40:22.754Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[2021-06-24T23:40:22.754Z]     at Module.load (internal/modules/cjs/loader.js:950:32)
[2021-06-24T23:40:22.754Z]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[2021-06-24T23:40:22.754Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
[2021-06-24T23:40:22.754Z]     at internal/main/run_main_module.js:17:47
[2021-06-24T23:40:22.754Z] Emitted 'error' event on Server instance at:
[2021-06-24T23:40:22.754Z]     at emitErrorNT (net.js:1347:8)
[2021-06-24T23:40:22.754Z]     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
[2021-06-24T23:40:22.754Z]   code: 'EADDRINUSE',
[2021-06-24T23:40:22.754Z]   errno: -98,
[2021-06-24T23:40:22.754Z]   syscall: 'listen',
[2021-06-24T23:40:22.754Z]   address: '::',
[2021-06-24T23:40:22.754Z]   port: 8200
[2021-06-24T23:40:22.754Z] }
[2021-06-24T23:40:23.455Z] + log 'Running benchmark ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js with agent...'
[2021-06-24T23:40:23.455Z] + msg='Running benchmark ././test/benchmarks/scripts/../001-transaction-and-span-no-stack-trace.js with agent...'
[2021-06-24T23:40:23.455Z] + '[' '!' -z '' ']'
[2021-06-24T23:40:23.455Z] + AGENT=1
...
```

*Something* else on that bare metal machine is using port 8200 when a node benchmark run is starting. Perhaps this is failed clean up from an earlier run of this or a separate activity on that same server. The benchmark CI runs of the node.js agent are few and far between, so it seems less likely it is from an earlier node.js benchmarks run.  8200 is the common default port for APM server, so it is feasible this is from some other benchmark run on the same server. I don't know of an easy way to get a time-ordered listing of all the activities running on those servers. Is there something in Jenkins for this?

Some ideas:
- List all process at the start of a run to try to identify who it might be that is using that port
- Work around the issue by letting our APM server start select a free port and pass that config to the running benchmark script to use.

I'm not pursuing this right now, unless the "occasional" occurrence starts getting in the way.

**Comment by trentm** [comment]
This is happening every time, I think, according to https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/

**Comment by trentm** [comment]
Note that a test run just now passed the Benchmarks step: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1009/pipeline/944

This one ran on a different metal worker:

```
[2021-08-09T16:35:42.163Z] Running on worker-1225339 in /var/lib/jenkins/workspace/dejs_apm-agent-nodejs-mbp_master
```

I haven't checked to see if the Benchmarks failures are all on the "worker-854309" metal worker.

**Comment by trentm** [comment]
For later investigation if this issue re-appears:

1. Find which worker the Benchmark build step ran on by grepping for "Running on worker-" in the console log. E.g. this line in https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/1018/console

```
09:53:19  Running on worker-854309 in /var/lib/jenkins/workspace/dejs_apm-agent-nodejs-mbp_master
```

2. SSH to that worker via the accessing instances docs in the infra repo. The worker IP is on the node page for that worker in jenkins.
3. Run `sudo netstat -nlp | grep LISTEN` to see which process might be listening on port 8200.  In this case it is the apm-server container. 
4. Run `sudo docker ps` to see if there are docker containers running.  
5. If there are, and they are old (there is no current jenkins build running on this worker), then `sudo docker kill ...` them.

**Comment by trentm** [comment]
I've killed the lingering containers running on worker-1095690 and worker-854309. I'm assuming that https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/1019/ will pass now. Closing for now. If/when this occurs we can re-open or open a new ticket to dive into it. If it happens from RUM again, then likely the fix is there.

**Comment by trentm** [comment]
> I'm assuming that https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/1019/ will pass now.

It did.
![Screen Shot 2021-08-12 at 12 23 22 PM](https://user-images.githubusercontent.com/46866/129256501-a5175113-34b4-4671-a343-81b4bc8d4cd1.png)

**Comment by trentm** [comment]
If/when we hit this again, @astorm suggested we change the port we use to avoid possible collision. It would mean:

- changing the value here: https://github.com/elastic/apm-agent-nodejs/blob/v3.20.0/test/benchmarks/utils/apm-server.js#L16
- and setting `ELASTIC_APM_SERVER_URL` in https://github.com/elastic/apm-agent-nodejs/blob/master/test/benchmarks/scripts/run-benchmarks.sh

**Comment by trentm** [comment]
The issues persist:

- Build https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/1023/ failed on 2021-08-16 with the same:

```
[2021-08-16T21:47:37.011Z] + node ././test/benchmarks/scripts/../utils/apm-server.js
[2021-08-16T21:47:37.011Z] events.js:377
[2021-08-16T21:47:37.011Z]       throw er; // Unhandled 'error' event
[2021-08-16T21:47:37.011Z]       ^
[2021-08-16T21:47:37.011Z] 
[2021-08-16T21:47:37.011Z] Error: listen EADDRINUSE: address already in use :::8200
[2021-08-16T21:47:37.011Z]     at Server.setupListenHandle [as _listen2] (net.js:1320:16)
```

From that build log, it was running on:

```
[2021-08-16T21:45:30.419Z] Running on worker-1225339 in /var/lib/jenkins/workspace/dejs_apm-agent-nodejs-mbp_master
```

That worker does **NOT** currently have an apm-server running on it:

```
trentm@worker-1225339:~$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Note that the other two workers currently *do*:

```
trentm@worker-854309:~$ sudo docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED        STATUS                  PORTS                                NAMES
a2698c8751e8   docker.elastic.co/apm/apm-server:7.13.1                "/usr/bin/tini -- /u…"   23 hours ago   Up 23 hours (healthy)   127.0.0.1:8200->8200/tcp             apm-server
408629911a72   docker.elastic.co/kibana/kibana:7.13.1                 "/bin/tini -- /usr/l…"   23 hours ago   Up 23 hours (healthy)   127.0.0.1:5601->5601/tcp             kibana
5f4b2b015f57   docker.elastic.co/elasticsearch/elasticsearch:7.13.1   "/bin/tini -- /usr/l…"   23 hours ago   Up 23 hours (healthy)   127.0.0.1:9200->9200/tcp, 9300/tcp   elasticsearch

trentm@worker-1095690:~$ sudo docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                    PORTS                                NAMES
b0c9be14aa5f   docker.elastic.co/apm/apm-server:7.13.1                "/usr/bin/tini -- /u…"   16 minutes ago   Up 16 minutes (healthy)   127.0.0.1:8200->8200/tcp             apm-server
bb510c349eb2   docker.elastic.co/kibana/kibana:7.13.1                 "/bin/tini -- /usr/l…"   16 minutes ago   Up 16 minutes (healthy)   127.0.0.1:5601->5601/tcp             kibana
b7570f766172   docker.elastic.co/elasticsearch/elasticsearch:7.13.1   "/bin/tini -- /usr/l…"   16 minutes ago   Up 16 minutes (healthy)   127.0.0.1:9200->9200/tcp, 9300/tcp   elasticsearch
```

Digging a bit, it looks like these are (again) from the RUM agent. Specifically I *think* from the .ci/scripts/load-testing.sh stage. The RUM agent's CI uses the "metal" workers for both benchmarks and a separate load testing stage: https://github.com/elastic/apm-agent-rum-js/blob/52f9118e587bef1831a743eee3a3166f9eba141a/Jenkinsfile#L257-L290

This load testing was added in https://github.com/elastic/apm-agent-rum-js/pull/959
Part of that discussion/PR work included a commit to *start* the `load-testing.sh` run with a `docker-compose -f ./dev-utils/docker-compose.yml down ...` to:

> Ensure the environment has been prepared and no leftovers from previous runs

This indicates to me that there was experience with the RUM load testing stage leaving stuff running... and I believe that "stuff" is the docker containers we see above -- including the APM server that is taking port 8200 and breaking the Node.js agent benchmark tests.

TODO:
- [ ] open a ticket on the RUM js agent to get the load-testing.sh script to clean up properly
- [ ] change the node.js benchmarks run to use a different APM server port to avoid this issue
