### ISSUE TITLE
Master branch tests broken

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-nodejs#2172]
Hello!

It seems [that the master branch tests are broken](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1000/pipeline) when testing with Apollo Server Express.

The relevant log lines appear to be as follows:

```
[2021-08-02T06:52:37.424Z] node_tests_1  | -- running test "node test/instrumentation/modules/apollo-server-express.test.js" with apollo-server-express

[2021-08-02T06:52:37.424Z] node_tests_1  | /app/test/instrumentation/modules/apollo-server-express.test.js:50

[2021-08-02T06:52:37.424Z] node_tests_1  |   apollo.start().then(function () {

[2021-08-02T06:52:37.424Z] node_tests_1  |          ^

[2021-08-02T06:52:37.424Z] node_tests_1  | 

[2021-08-02T06:52:37.424Z] node_tests_1  | TypeError: apollo.start is not a function

[2021-08-02T06:52:37.424Z] node_tests_1  |     at Test.<anonymous> (/app/test/instrumentation/modules/apollo-server-express.test.js:50:10)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at Test.bound [as _cb] (/app/node_modules/tape/lib/test.js:96:32)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at Test.run (/app/node_modules/tape/lib/test.js:115:31)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at Test.bound [as run] (/app/node_modules/tape/lib/test.js:96:32)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at Immediate.next (/app/node_modules/tape/lib/results.js:88:19)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at runCallback (timers.js:705:18)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at tryOnImmediate (timers.js:676:5)

[2021-08-02T06:52:37.424Z] node_tests_1  |     at processImmediate (timers.js:658:5)

[2021-08-02T06:52:37.424Z] node_tests_1  | -- detected failing command, flushing stdout...

```

**Comment by astorm** [comment]
Local Run:

% TAV=apollo-server-express ./node_modules/.bin/tav --compat
Testing compatibility with apollo-server-express:
✔ 3.1.1
✔ 3.1.0
✔ 3.0.2
✔ 3.0.1
✔ 3.0.0

✔ 2.25.0
✔ 2.24.1
✔ 2.23.0
✔ 2.22.2
✔ 2.21.2
✔ 2.20.0
✔ 2.19.2
✔ 2.18.2
✔ 2.17.0
✔ 2.16.1
✔ 2.15.1

✔ 2.25.0
✔ 2.24.1
✔ 2.23.0
✔ 2.22.2
✔ 2.21.2
✔ 2.20.0
✔ 2.19.2
✔ 2.18.2
✔ 2.17.0
✔ 2.16.1
✔ 2.15.1
✔ 2.14.5
✔ 2.13.1
✔ 2.12.0
✔ 2.11.0
✔ 2.10.1
✔ 2.9.16
✖ 2.8.2
✖ 2.7.2
✖ 2.6.9
✖ 2.5.1
✖ 2.4.8
✖ 2.3.3
✔ 2.1.0
✖ 2.0.7

✔ 2.25.0
✔ 2.24.1
✔ 2.23.0
✔ 2.22.2
✔ 2.21.2
✔ 2.20.0
✔ 2.19.2
✔ 2.18.2
✔ 2.17.0
✔ 2.16.1
✔ 2.15.1
✔ 2.14.5
✔ 2.13.1
✔ 2.12.0
✔ 2.11.0
✔ 2.10.1
✔ 2.9.16
✖ 2.8.2
✖ 2.7.2
✖ 2.6.9
✖ 2.5.1
✖ 2.4.8
✖ 2.3.3
✔ 2.1.0
✖ 2.0.7

✔ 2.25.0
✔ 2.24.1
✔ 2.23.0
✔ 2.22.2
✔ 2.21.2
✔ 2.20.0
✔ 2.19.2
✔ 2.18.2
✔ 2.17.0
✔ 2.16.1
✔ 2.15.1
✔ 2.14.5
✔ 2.13.1
✔ 2.12.0
✔ 2.11.0
✔ 2.10.1
✔ 2.9.16
✖ 2.8.2
✖ 2.7.2
✖ 2.6.9
✖ 2.5.1
✖ 2.4.8
✖ 2.3.3
✔ 2.1.0
✖ 2.0.7

**Comment by astorm** [comment]
@cachedout should be fixed -- if you're still seeing nightly failures you know what to do.
