### ISSUE TITLE
test failure with @elastic/elasticsearch@7.14.1

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2310]
`@elastic/elasticsearch@7.14.1` was recently released:

```
$ npm info -j @elastic/elasticsearch
...
"7.14.1": "2021-08-30T13:09:49.668Z"`
...
```

And it breaks tests (for all node versions):

```
% npm ls @elastic/elasticsearch
elastic-apm-node@3.20.0 /Users/trentm/el/apm-agent-nodejs12
└── @elastic/elasticsearch@7.14.1

$ node test/instrumentation/modules/@elastic/elasticsearch.test.js
...
# request.abort() works
ok 250 got error
ok 251 error is RequestAbortedError
ok 252 have an elasticsearch span
not ok 253 sent an error to APM server
  ---
    operator: ok
    expected: true
    actual:   undefined
    at: done (/Users/trentm/el/apm-agent-nodejs12/test/instrumentation/modules/@elastic/elasticsearch.test.js:399:13)
    stack: |-
      Error: sent an error to APM server
          at Test.assert [as _assert] (/Users/trentm/el/apm-agent-nodejs12/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/Users/trentm/el/apm-agent-nodejs12/node_modules/tape/lib/test.js:91:32)
          at Test.assert (/Users/trentm/el/apm-agent-nodejs12/node_modules/tape/lib/test.js:423:10)
          at Test.bound [as ok] (/Users/trentm/el/apm-agent-nodejs12/node_modules/tape/lib/test.js:91:32)
          at done (/Users/trentm/el/apm-agent-nodejs12/test/instrumentation/modules/@elastic/elasticsearch.test.js:399:13)
          at Timeout._onTimeout (/Users/trentm/el/apm-agent-nodejs12/test/_mock_http_client.js:65:7)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)
  ...
/Users/trentm/el/apm-agent-nodejs12/test/instrumentation/modules/@elastic/elasticsearch.test.js:400
          t.ok(err.id, 'err.id')
                   ^

TypeError: Cannot read property 'id' of undefined
    at done (/Users/trentm/el/apm-agent-nodejs12/test/instrumentation/modules/@elastic/elasticsearch.test.js:400:20)
    at Timeout._onTimeout (/Users/trentm/el/apm-agent-nodejs12/test/_mock_http_client.js:65:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by trentm** [comment]
Okay... this is the potential surprise that we had coming with our test from the change in #2188. That PR added a workaround for https://github.com/elastic/elasticsearch-js/issues/1517 *just for version 7.14.0*:

```js
        if (semver.eq(esVersion, '7.14.0')) {
          // https://github.com/elastic/elasticsearch-js/issues/1517
          t.ok(!err, 'no APM error reported for abort because elastic/elasticsearch-js#1517')
```

That elasticsearch-js issue has been fixed (in https://github.com/elastic/elasticsearch-js/pull/1534), but that fix is *not* a part of v7.14.1.  That fix was backported just to the "7.15" branch of elasticsearch-js.  Therefore we should change our test guard here to be if the ES client version is any 7.14.x version.
