### ISSUE TITLE
lambda wrapper doesn't handle uncaughtException or unhandleRejection

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2379]
A lambda handler like this:

```js
exports.handler = apm.lambda(function handlerThrows3 (event, context) {
  console.warn('XXX start 100ms timeout')
  setTimeout(function () {
    console.warn('XXX go boom3')
    throw new Error('boom3')
  }, 100)
})
```

results in an uncaught exception. The current experimental Lambda wrapping doesn't trap this.

* * *

The Lambda Runtime does this:

```typescript
  private _setErrorCallbacks(invokeId: string): void {
    this.errorCallbacks.uncaughtException = (error: Error): void => {
      this.client.postInvocationError(error, invokeId, () => {
        process.exit(129);
      });
    };
    this.errorCallbacks.unhandledRejection = (error: Error): void => {
      this.client.postInvocationError(error, invokeId, () => {
        process.exit(128);
      });
    };
  }
```

I.e. it notes the error, then `process.exit(SPECIAL_VALUE)`s. I'm not sure if the runtime has overridden or is somehow handling those process.exit values. My limited observation is that the runtime node process is *not* restarting, because a subsequent function invocation uses the same VM and doesn't run through the APM agent startup again.

Some things to think about when handling this:

- [ ] Does the APM agent's optional `uncaughtException` handler (in agent.js) collide here? Ditto for a coming `unhandleRejection` handler.
- [ ] Do we have a timing race with `this.client.postInvocationError(...)` here if we want to note the error and send data to the extension?

**Comment by trentm** [comment]
Some more details on my recent testing of this.

Summary:

| error case          | description                                | lambda response unchanged? | transaction reported? | error reported? |
| ------------------- | ------------------------------------------ | -------------------------- | --------------------- | --------------- |
| exception           | throw at top-level in a non-async function | yes (1) | yes | yes |
| uncaughtException   | throw in async part of non-async function  | yes (1) | no | no |
| unhandledRejection1 | rejecting a promise not handled with `.catch()` | yes | no | no |
| unhandledRejection2 | throwing inside an async function without a catch block | yes (1) | yes | yes |

Note (1): While the Lambda handler response not changed meaningfully (a good thing), there
is a change in the stacktrace due to the instrumentation. This is acceptable.


## exception (good)

Handler:

```js
exports.handler = function errorThrowSync () {
  throw new Error('errorThrowSync')
}
```

Response without agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorThrowSync",
  "trace": [
    "Error: errorThrowSync",
    "    at Runtime.errorThrowSync [as handler] (/var/task/index.js:24:9)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Response with agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorThrowSync",
  "trace": [
    "Error: errorThrowSync",
    "    at Runtime.errorThrowSync (/var/task/index.js:24:9)",
    "    at Runtime.wrappedLambda [as handler] (/opt/nodejs/node_modules/elastic-apm-node/lib/lambda.js:457:19)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

## uncaughtException (needs improvement)

Handler:

```js
exports.handler = function errorUncaughtException () {
  setImmediate(() => {
    throw new Error('errorUncaughtException')
  })
}
```

Response without agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorUncaughtException",
  "trace": [
    "Error: errorUncaughtException",
    "    at Immediate.<anonymous> (/var/task/index.js:28:11)",
    "    at processImmediate (internal/timers.js:464:21)"
  ]
}
```

Response with agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorUncaughtException",
  "trace": [
    "Error: errorUncaughtException",
    "    at Immediate.<anonymous> (/var/task/index.js:28:11)",
    "    at processImmediate (internal/timers.js:464:21)",
    "    at process.callbackTrampoline (internal/async_hooks.js:130:17)"
  ]
}
```

The APM transaction and error are **not** reported. The log includes the following, which shows that:
- a transaction was *started*
- the unhandled exception was *noticed* by the APM agent
- processing in the VM stopped very soon after that and the VM was shutdown

```
2022-03-04T21:33:02.918000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce {"log.level":"debug","@timestamp":"2022-03-04T21:33:02.918Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"start trace {\"trans\":\"ff92d23c80451eb5\",\"trace\":\"866761053c3d9baa7ab0f44546cf8a87\",\"name\":\"unnamed\",\"type\":\"lambda\",\"subtype\":null,\"action\":null}"}
...
2022-03-04T21:33:02.920000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce {"log.level":"debug","@timestamp":"2022-03-04T21:33:02.919Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"error":{"type":"Error","message":"errorUncaughtException","stack_trace":"Error: errorUncaughtException\n    at Immediate.<anonymous> (/var/task/index.js:28:11)\n    at processImmediate (internal/timers.js:464:21)\n    at process.callbackTrampoline (internal/async_hooks.js:130:17)"},"message":"Elastic APM caught unhandled exception"}
2022-03-04T21:33:02.920000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce 2022-03-04T21:33:02.920Z	46ba6dc2-107a-488d-aae4-3c85cf50b362	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"errorUncaughtException","stack":["Error: errorUncaughtException","    at Immediate.<anonymous> (/var/task/index.js:28:11)","    at processImmediate (internal/timers.js:464:21)","    at process.callbackTrampoline (internal/async_hooks.js:130:17)"]}
2022-03-04T21:33:03.217000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce 2022/03/04 21:33:03 Received log event platform.runtimeDone
...
2022-03-04T21:33:03.277000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce 2022/03/04 21:33:03 Received event: {
2022-03-04T21:33:03.277000+00:00 2022/03/04/[$LATEST]4ebd843eafdd4ab392a00c670c5060ce 	"eventType": "SHUTDOWN",
```

## unhandledRejection1 (needs improvement)

Handler:

```js
exports.handler = function errorUnhandledRejection1 () {
  new Promise((resolve, reject) => {
    setTimeout(reject, 100, 'boom')
  })
}
```

Response without agent (pretty-printed):

```
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "boom",
  "trace": [
    "Runtime.UnhandledPromiseRejection: boom",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:400:28)",
    "    at processPromiseRejections (internal/process/promises.js:245:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
  ]
}
```

Response with agent (pretty-printed): same.

No APM transaction or error is reported. I don't have a log snippet. I suspect the APM agent just completely didn't see this.


## unhandledRejection2 (good)

Handler:

```js
exports.handler = async function errorUnhandledRejection2 () {
  throw new Error('errorUnhandledRejection2')
}
```

Response without agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorUnhandledRejection2",
  "trace": [
    "Error: errorUnhandledRejection2",
    "    at Runtime.errorUnhandledRejection2 [as handler] (/var/task/index.js:37:9)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Response with agent (pretty-printed):

```
{
  "errorType": "Error",
  "errorMessage": "errorUnhandledRejection2",
  "trace": [
    "Error: errorUnhandledRejection2",
    "    at Runtime.errorUnhandledRejection2 (/var/task/index.js:37:9)",
    "    at Runtime.wrappedLambda [as handler] (/opt/nodejs/node_modules/elastic-apm-node/lib/lambda.js:457:19)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

An APM transaction and error **are** reported.

**Comment by trentm** [comment]
> My limited observation is that the runtime node process is _not_ restarting, because a subsequent function invocation uses the same VM and doesn't run through the APM agent startup again.

Recent observation: for an async throw that results in an uncaught exception a "shutdown" event is send to the Lambda extension (is that part of the Runtime API?). On a subsequent invocation, then same VM is used, but I think it is a new runtime process -- at least the 'pid' for the APM agent is different.


* * *

One idea could be to quickly write some error info to disk and have the extension send those error details to APM server "some time later". Or perhaps the error *could* be sync reported to the extension and then the extension could take the time to pass that on when handling the Runtime API "shutdown" event?

**Comment by trentm** [comment]
With the changes in #3285 the APM agent Lambda layer (along with a Lambda extension layer with the required support -- currently not yet released) will reporting a transaction with `transaction.outcome = "failure"` if the user's Lambda invocation crashes, times out, or has an uncaughtException or unhandledRejection.  That's a good thing.

However, it will *not* create an APM error event and report that. The reason is that there will always be a race between (a) the APM agent attempting to gather the error info, send the event to the Lambda extension via a typical intake request, then flush and the Lambda Runtime doing `.postInvocationError(error).then(() => { process.exit(...) }` as shown in the [description above](https://github.com/elastic/apm-agent-nodejs/issues/2379#issue-1029593687). Reporting an APM error event could be useful because it could provide a stack trace.

For now, I am not proposing doing subsequent work to improve on this. Beating that race would likely require something like:

- adding new `POST /register/error` support on the Lambda extension
- either limiting the APM agent's error gathering so it is faster (gathering a stack trace is fairly slow) and/or looking into *delaying* the Lambda Runtime's `unhandledException` handler until the APM agent can do its own

For now, at least, the user will see failed transaction events, and the Lambda log (in CloudWatch -- possibly ingested into Elastic separately) will show the traceback (as shown in the examples above).
