### ISSUE TITLE
Cannot create property 'Symbol(reported)' on 

### ISSUE THREAD

**Issue by Sonosar** [elastic/apm-agent-nodejs#239]
When custom errors are thrown apm will write something like 

`Cannot create property 'Symbol(reported)' on number '500'
    at /Users/user/Projects/proj/projnode_modules/elastic-apm-node/lib/instrumentation/modules/express.js:34:33
    at Layer.handle_error (/Users/user/Projects/proj/projnode_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:315:13)
    at /Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:335:12)
    at Function.process_params (/Users/user/Projects/proj/projnode_modules/elastic-apm-node/lib/instrumentation/modules/express.js:48:19)
    at next (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/user/Projects/proj/projnode_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:315:13)
    at /Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:335:12)
    at Function.process_params (/Users/user/Projects/proj/projnode_modules/elastic-apm-node/lib/instrumentation/modules/express.js:48:19)
    at Immediate.next (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/user/Projects/proj/projnode_modules/express/lib/router/index.js:635:15)
    at Immediate.elasticAPMCallbackWrapper (/Users/user/Projects/proj/projnode_modules/elastic-apm-node/lib/instrumentation/index.js:134:27)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

This log is apm specific , so I'm curious whether this is the result of apm failing to handle error properly?

**Comment by Qard** [comment]
Thanks for reporting this. It looks like you are calling `next(...)` with a non-error. I've got a fix incoming in #240 so invalid error types won't cause this failure.

**Comment by watson** [comment]
This have now been fixed in v1.0.2
