### ISSUE TITLE
lambda: if extension is down, agent eventually causes `null` function response

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2598]
If the Elastic lambda extension is missing in a Lambda function instrumented with the APM Node.js agent, then the function response will become `null` after a few requests.

```js
exports.handler = function styleCallback (event, context, callback) {
  callback(null, 'hi from styleCallback')
}
```

After a few requests:

```
% curl -i https://REDACTED.execute-api.us-west-2.amazonaws.com/defaulttrentstage/trentm-play-fn1
HTTP/2 200
date: Fri, 04 Mar 2022 23:57:41 GMT
content-type: application/json
content-length: 4
apigw-requestid: Oe8aTiyzPHcEPzQ=

null%
```

The trace log includes:

```
{"log.level":"trace","@timestamp":"2022-03-04T23:57:40.995Z","log":{"logger":"elastic-apm-node"},"event.module":"apmclient","reqId":"dfcd904ca06bf02a236df047f003adad","timeline":[[1.276283,"completePart intakeReq","connect ECONNREFUSED 127.0.0.1:8200"]],"bytesWritten":10,"backoffDelayMs":14453.237806792018,"ecs":{"version":"1.6.0"},"error":{"type":"Error","message":"connect ECONNREFUSED 127.0.0.1:8200","stack_trace":"Error: connect ECONNREFUSED 127.0.0.1:8200\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17)"},"message":"conclude intake request: error"}
```

in particular `"backoffDelayMs":14453.237806792018`. I believe that may be a cause of the issue here.

However, **this may also just be the same issue as** https://github.com/elastic/apm-agent-nodejs/issues/2166 which will be fixed soon when https://github.com/elastic/apm-agent-nodejs/pull/2586 goes in. I'll recheck then.

**Comment by trentm** [comment]
I have a fix for this, with this patch to the http client (apm-nodejs-http-client.git):

```diff
diff --git a/index.js b/index.js
index 1a30978..b70e747 100644
--- a/index.js
+++ b/index.js
@@ -771,9 +771,18 @@ Client.prototype._destroy = function (err, cb) {
 // Return the appropriate backoff delay (in milliseconds) before a next possible
 // request to APM server.
 // Spec: https://github.com/elastic/apm/blob/main/specs/agents/transport.md#transport-errors
+//
+// In a Lambda environment, a backoff delay can be harmful: The backoff
+// setTimeout is unref'd, to not hold the process open. A subsequent Lambda
+// function invocation during that timer will result in no active handles and
+// a process "beforeExit" event. That event is interpreted by the Lambda Runtime
+// as "the Lambda function callback was never called", and it terminates the
+// function and responds with `null`.  The solution is to never backoff in a
+// Lambda environment -- we expect and assume the Lambda extension is working,
+// and pass responsibility for backoff to the extension.
 Client.prototype._getBackoffDelay = function (isErr) {
   let reconnectCount = this._backoffReconnectCount
-  if (isErr) {
+  if (isErr && !isLambdaExecutionEnvironment) {
     this._backoffReconnectCount++
   } else {
     this._backoffReconnectCount = 0
```

This depends on the https://github.com/elastic/apm-nodejs-http-client/pull/178 work, so I will wait for that to go in before putting up a PR.
