### ISSUE TITLE
spurious "not ok 25 send-a-span.js did not error

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3111]

**Comment by trentm** [comment]
# 2023-06-05 in `test-vers (19)`

https://github.com/elastic/apm-agent-nodejs/actions/runs/5180230985/jobs/9334144249

```
# error.log.stacktrace
ok 21 capture-error-string.js did not error
ok 22 APM server got event metadata object
ok 23 first error.log.stacktrace top frame is as expected
ok 24 second error.log.stacktrace top frame is as expected
# span.stacktrace
not ok 25 send-a-span.js did not error
  ---
    operator: error
    at: done (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/stacktraces/stacktraces.test.js:185:11)
    stack: |-
      Error: Command failed: /opt/hostedtoolcache/node/19.9.0/x64/bin/node fixtures/send-a-span.js
      
          at ChildProcess.exithandler (node:child_process:419:12)
          at ChildProcess.emit (node:events:513:28)
          at maybeClose (node:internal/child_process:1098:16)
          at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ...
/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/stacktraces/stacktraces.test.js:186
        t.ok(server.events[0].metadata, 'APM server got event metadata object')
                              ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at done (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/stacktraces/stacktraces.test.js:186:31)
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

Node.js v19.9.0

/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/test.js:182
    if (err) throw err
             ^

Error: non-zero error code
    at WriteStream.onClose (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/test.js:65:25)
    at WriteStream.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ENONZERO',
  exitCode: 1
}

Node.js v19.9.0
Error: Process completed with exit code 1.
```
