### ISSUE TITLE
AWS SQS tests are failing with recent @aws-sdk/client-sqs@3.446.0

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3716]
We are having the exact same issue as https://github.com/elastic/apm-agent-nodejs/issues/3324 but in this case is the package affected is `@aws-sdk/client-sqs` client instead of `aws-sdk`.

**TL;DR**
The SQS client switched from XML format to JSON and `localstack` does not support this format in the responses yet. 

Versions affected are 
```
"3.446.0": "2023-11-08T20:14:19.118Z",
"3.447.0": "2023-11-09T02:23:02.035Z"
```

https://github.com/elastic/apm-agent-nodejs/issues/3324 was solved because there was a new release reverting back to XML and we omit the bad release for testing. As for now the failing versions are the 2 latest ones so we could try to test up to the latest working and avoid testing on higher versions until `localstack` supports JSON. This option was commented [here](https://github.com/elastic/apm-agent-nodejs/issues/3324#issuecomment-1539208381)

More info on localstack JSON suport: https://github.com/localstack/localstack/pull/8268

**Comment by trentm** [comment]
An example of the failure is here: https://github.com/elastic/apm-agent-nodejs/actions/runs/6812004416/job/18523493535?pr=3715

```
...
docker-node_tests-1  | -- required packages ["@aws-sdk/client-sqs@3.447.0"]
docker-node_tests-1  | -- installing ["@aws-sdk/client-sqs@3.447.0"]
docker-node_tests-1  | -- running test "node test/instrumentation/modules/@aws-sdk/client-sqs.test.js" with @aws-sdk/client-sqs
docker-node_tests-1  | -- detected failing command, flushing stdout...
docker-node_tests-1  | TAP version 13
docker-node_tests-1  | # @aws-sdk/client-sqs fixtures
docker-node_tests-1  | # simple SQS V3 usage scenario (fixtures/use-client-sqs.js)
docker-node_tests-1  | not ok 1 fixtures/use-client-sqs.js exited successfully: err=Error: Command failed: /usr/local/bin/node fixtures/use-client-sqs.js 
docker-node_tests-1  |   ---
docker-node_tests-1  |     operator: error
docker-node_tests-1  |     at: done (/app/test/_utils.js:353:17)
docker-node_tests-1  |     stack: |-
docker-node_tests-1  |       Error: Command failed: /usr/local/bin/node fixtures/use-client-sqs.js
docker-node_tests-1  |       
docker-node_tests-1  |           at ChildProcess.exithandler (node:child_process:422:12)
docker-node_tests-1  |           at ChildProcess.emit (node:events:514:28)
docker-node_tests-1  |           at maybeClose (node:internal/child_process:1105:16)
docker-node_tests-1  |           at ChildProcess._handle.onexit (node:internal/child_process:305:5)
docker-node_tests-1  |   ...
docker-node_tests-1  | # stdout:
docker-node_tests-1  | # |{"log.level":"info","@timestamp":"2023-11-09T12:54:11.127Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.1.0","env":{"pid":285,"proctitle":"/usr/local/bin/node","os":"linux 6.2.0-1015-azure","arch":"x64","host":"9ae79c53e48f","timezone":"UTC+00","runtime":"Node.js v20.9.0"},"config":{"serviceName":{"source":"start","value":"use-client-sqs","commonName":"service_name"},"serviceVersion":{"source":"default","value":"4.1.0","commonName":"service_version"},"serverUrl":{"source":"environment","value":"http://localhost:38233/","commonName":"server_url"},"logLevel":{"source":"start","value":"info","commonName":"log_level"},"captureExceptions":{"source":"start","value":false},"centralConfig":{"source":"environment","value":false,"sourceValue":"false"},"metricsInterval":{"source":"environment","value":0,"sourceValue":"0s"},"cloudProvider":{"source":"environment","value":"none"},"stackTraceLimit":{"source":"start","value":4}},"activationMethod":"require","message":"Elastic APM Node.js Agent v4.1.0"}
docker-node_tests-1  | # |{"log.level":"error","@timestamp":"2023-11-09T12:54:11.396Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","error":{"type":"SyntaxError","message":"Unexpected token '<', \"<?xml vers\"... is not valid JSON\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.","stack_trace":"SyntaxError: Unexpected token '<', \"<?xml vers\"... is not valid JSON\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.\n    at JSON.parse (<anonymous>)\n    at /app/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:1980:21\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async parseErrorBody (/app/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:1985:19)"},"message":"useClientSQS rejected"}
docker-node_tests-1  | # stderr:
docker-node_tests-1  | # |
docker-node_tests-1  | # skip checkApmServer because script errored out
docker-node_tests-1  | # simple SQS V3 with ESM (fixtures/use-client-sqs.mjs)
docker-node_tests-1  | # SKIP node v20.9.0 is not supported by this fixture (requires: ^14.13.1 || ^16.0.0 || ^18.1.0 <20)
docker-node_tests-1  | 
docker-node_tests-1  | 1..1
docker-node_tests-1  | # tests 1
docker-node_tests-1  | # pass  0
docker-node_tests-1  | # fail  1
...
```

**Comment by david-luna** [comment]
Fixed in #3717

**Comment by trentm** [comment]
@david-luna With this closed, do we have an issue or some way to know to re-enable tests for recent client-sqs releases when the localstack issue is fixed?

**Comment by david-luna** [comment]
Not yet @trentm. I'm about to open one

**Comment by david-luna** [comment]
Here it is https://github.com/elastic/apm-agent-nodejs/issues/3719
