### ISSUE TITLE
tests failing for `aws-sdk@2.1491.0` 

### ISSUE THREAD

**Issue by david-luna** [elastic/apm-agent-nodejs#3718]
TAV tests revealed there is a problem in instrumentation of `aws-sdk` module
https://github.com/elastic/apm-agent-nodejs/actions/runs/6813128313/job/18527021241

There are errors in the transaction
```
not ok 43 got the transaction
  ---
    operator: ok
    expected: true
    actual:   undefined
```

and also with the spans 
```
not ok 49 sendMessageBatch
  ---
    operator: deepEqual
    expected: |-
      { name: 'SQS SEND_BATCH to elasticapmtest-queue-1.fifo', type: 'messaging', subtype: 'sqs', action: 'send_batch', context: { service: { target: { type: 'sqs', name: 'elasticapmtest-queue-1.fifo' } }, destination: { address: 'localhost', port: 4566, cloud: { region: 'us-east-2' }, service: { type: '', name: '', resource: 'sqs/elasticapmtest-queue-1.fifo' } }, message: { queue: { name: 'elasticapmtest-queue-1.fifo' } } }, outcome: 'success' }
    actual: |-
      {}
```

It's failing for the latest versions
```bash
npm view aws-sdk time --json
[
 ...
  "2.1491.0": "2023-11-08T19:36:32.741Z",
  "2.1492.0": "2023-11-09T02:34:42.175Z"
]
```

Although is not failing on with parsing errors it's worth mentioning they've also moved to JSON protocol
https://github.com/aws/aws-sdk-js/blob/95200971506b604934f73003c7a7c9d1515193ab/CHANGELOG.md?plain=1#L18

**Comment by david-luna** [comment]
Most likely is the protocol change that broke the tests but I'll double check. If confirmed we should proceed with the same approach as #3716 (disable tests for newer versions and re-enable when `localstack` supports the new )

**Comment by david-luna** [comment]
Adding a simple log when `useSQS` rejects

```diff
diff --git a/test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js b/test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js
index 3f3ba863..f442c312 100644
--- a/test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js
+++ b/test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js
@@ -240,6 +240,7 @@ async function main() {
     await useSQS(sqsClient, queueName);
     tx.end();
   } catch (err) {
+    console.error('useSQS Error', err);
     tx.setOutcome('failure');
     process.exitCode = 1;
   }
```

We can spot a 500 response from `localstak`
```
# (node:49845) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
#
# Please migrate your code to use AWS SDK for JavaScript (v3).
# For more information, check the migration guide at https://a.co/7PzMCcy
# (Use `node --trace-warnings ...` to show where the warning was created)
# useSQS Error Error [UnknownError]
# at Request.extractError (/Users/david/Documents/repos/el/apm-agent-nodejs/node_modules/aws-sdk/lib/protocol/json.js:80:27)
# at Request.callListeners (/Users/david/Documents/repos/el/apm-agent-nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
# at Request.emit (/Users/david/Documents/repos/el/apm-agent-nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
# at Request.emit (/Users/david/Documents/repos/el/apm-agent-nodejs/node_modules/aws-sdk/lib/request.js:686:14) {
# code: 'UnknownError',
# statusCode: 500,
# time: 2023-11-14T14:58:39.998Z,
# requestId: undefined,
# retryable: true
# }
```

So we should proceed as we did in #3324 and follow up with #3719
