### ISSUE TITLE
Agent doesn't capture uncaught exceptions or unhandled rejections

### ISSUE THREAD

**Issue by Vectarian-Jorge** [elastic/apm-agent-nodejs#3960]
**Describe the bug**

Suddenly my Express applications do not capture errors or exceptions that cause the application to crash. Up until the 21st of February I can see both in the Error tab of the APM and in the Discover tool of ELK that there were crashes reported due to silly mistakes, like a missing environment variable. But nothing since then. And I've tried to crash the application deliberately adding `throw new Error('Boom')` and `Promise.reject(new Error('Kaboom'))` and neither is reported by the APM.

Investigating any possible changes I've made I can only think of upgrading the agent's version from 3.42.0 to 4.3.0. But I've tried with the old version and it behaves the same way.

**To Reproduce**

I haven't created a minimal reproduction case.

**Expected behavior**

Uncaught exceptions and unhandled rejections being reported by the agent so that they can be monitored in the APM tool of ELK.

**Environment (please complete the following information)**

- OS: Linux and MacOS
- Node.js version: 16.16.0
- APM Server version: 7.17.8
- Agent version: 3.42.0 and 4.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
In particular, I have a `init-elastic-apm.ts` file where I start the agent with a config dependent on some environment variables. Then the first line of my `index.ts` file is `import apm from 'elastic-apm-node'`.
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
import { hostname } from 'node:os';
import pkg from '../../package.json' assert { type: 'json' };
{
	serviceName: pkg.name.split('/')[1],
	serviceVersion: pkg.version,
	serviceNodeName: hostname(),
	environment: process.env['APP_ENV'],
	serverUrl: process.env['ELK_KIBANA_URL'],
	captureBody: 'all',
	captureExceptions: true, // <-- I've tried with default and explicit `captureExceptions`
}
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
"@aws-sdk/client-s3": "3.245.0",
"@aws-sdk/client-timestream-write": "3.245.0",
"@bluesialia/express-graphql": "0.15.0",
"@elastic/ecs-pino-format": "1.5.0",
"@sentry/node": "7.103.0",
"bcryptjs": "2.4.3",
"body-parser": "1.20.1",
"compression": "1.7.4",
"cors": "2.8.5",
"dotenv": "16.3.1",
"elastic-apm-node": "3.42.0",
"express": "4.18.2",
"express-async-errors": "3.1.1",
"extract-files": "13.0.0",
"firebase-admin": "11.10.1",
"google-auth-library": "8.7.0",
"graphql": "16.6.0",
"graphql-scalars": "1.20.1",
"graphql-upload": "13.0.0",
"graphql-ws": "5.11.2",
"http-status": "1.6.1",
"jszip": "3.10.1",
"knex": "2.4.0",
"modern-async": "1.1.3",
"node-fetch": "3.3.2",
"objection": "3.1.4",
"objection-paginator": "0.7.1",
"paddle-sdk": "3.2.0",
"pg": "8.8.0",
"pino": "8.17.1",
"stringify-object": "5.0.0",
"wasmagic": "0.0.32"
```
</details>

**Comment by Vectarian-Jorge** [comment]
Added a minimal example. Those 3 files. Just run `node index.js` with any of the throws uncommented. It'll crash and the agent won't report it.

**Comment by david-luna** [comment]
Hi @Vectarian-Jorge 

I've run you example uncommenting the li within the request handler but haven't been able to reproduce. I can see the error in Kibana.

![Screenshot 2024-04-25 at 16 25 41](https://github.com/elastic/apm-agent-nodejs/assets/999029/907429d2-0db6-4614-b237-8034ed8cb83f)

Are you able to get the initial line of log output from the APM agent? It looks something like this:
```
{"log.level":"info","@timestamp":"2024-04-25T14:35:50.282Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.3","env":{"pid":30004,"proctitle":"node","os":"darwin 23.4.0","arch":"arm64","host":"moonlocal.local","timezone":"UTC+0200","runtime":"Node.js v18.16.0"},"config":{"environment":{"source":"start","value":"local"},"logLevel":{"source":"environment","value":"trace","commonName":"log_level"},"serverUrl":{"source":"environment","value":"https://eah-demo-testing.apm.us-central1.gcp.cloud.es.io/","commonName":"server_url"},"secretToken":{"source":"environment","value":"[REDACTED]","commonName":"secret_token"},"serviceName":{"source":"environment","value":"expresscmp-elastic1","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"import","dependencies":{"elastic-apm-node":"^4.5.0","express":"^4.19.2"},"startTrace":["at Agent.start (/Users/david/Documents/repos/issues/el-apm-node-3960/node_modules/elastic-apm-node/lib/agent.js:294:11)","at file:///Users/david/Documents/repos/issues/el-apm-node-3960/apm.js:3:5","at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"],"message":"Elastic APM Node.js Agent v4.5.3"}
```

If so, check if the line contains something like
```
"config": { "captureExceptions": { "source": "start", "value": false }
```

This is to check there is no other source setting the configuration option.

**Comment by david-luna** [comment]
Also if you can make local edits, you can apply this change to log if the agent's exception handler is properly attached to the process.

```diff
diff --git a/lib/agent.js b/lib/agent.js
index 2a1e26df..64fe1c59 100644
--- a/lib/agent.js
+++ b/lib/agent.js
@@ -776,6 +776,8 @@ Agent.prototype.handleUncaughtExceptions = function (cb) {
     });
   };
 
+  console.log('XXX attaching uncaughtException handler to process')
+
   process.on('uncaughtException', this._uncaughtExceptionListener);
 };
```
to "node_modules/elastic-apm-node/lib/agent.js", restart, and reproduce. Then post here full log to check if this new line appears

**Comment by Vectarian-Jorge** [comment]
This is the initial log line:
```
{"log.level":"info","@timestamp":"2024-04-29T07:49:31.180Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.0","env":{"pid":99719,"proctitle":"node","os":"darwin 23.4.0","arch":"arm64","host":"REDACTED","timezone":"UTC+0100","runtime":"Node.js v20.11.0"},"config":{"captureExceptions":{"source":"start","value":true},"environment":{"source":"start","value":"local"},"logLevel":{"source":"default","value":"info","commonName":"log_level"},"serverUrl":{"source":"start","value":"REDACTED","commonName":"server_url"},"serviceName":{"source":"default","value":"experiment","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"import","message":"Elastic APM Node.js Agent v4.5.0"}
```

This is with `captureExceptions: true` explicitly defined in the APM start options. If I remove the property `"captureExceptions": { "source": "start", "value": true }` does not show up in the log line.

With the file `node_modules/elastic-apm-node/lib/agent.js` modified as instructed the first 3 lines printed to console are:
```
{"log.level":"info","@timestamp":"2024-04-29T07:55:22.430Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.0","env":{"pid":99904,"proctitle":"node","os":"darwin 23.4.0","arch":"arm64","host":"REDACTED","timezone":"UTC+0100","runtime":"Node.js v20.11.0"},"config":{"captureExceptions":{"source":"start","value":true},"environment":{"source":"start","value":"local"},"logLevel":{"source":"default","value":"info","commonName":"log_level"},"serverUrl":{"source":"start","value":"REDACTED","commonName":"server_url"},"serviceName":{"source":"default","value":"experiment","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"import","message":"Elastic APM Node.js Agent v4.5.0"}
XXX attaching uncaughtException handler to process
Example app listening on port 3000
```

The following line would be the error `Error: Kaboom` and its stacktrace if I triggered.

If I'm not mistaken. These outputs are what they should be, yet still no errors show on the APM panel.

I think I read somewhere that the agent prints something to console whenever it captures a fatal error and sends it to ELK. Is that correct? If that's the case I don't see that log either.

**Comment by david-luna** [comment]
Hi @Vectarian-Jorge 

as your logs show the exception handler is set when the agent starts so we can assume the agent starts correctly. Next thing to try is to set the log level to `trace` to see if there are any issues related to other components.

You can start you example with the defined log level like this
```sh
ELASTIC_APM_LOG_LEVEL=trace node index.js
```
Ref: https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#log-level

once you got the logs please paste them here :)

**Comment by Vectarian-Jorge** [comment]
I see the line that says `Sending error to Elastic APM: {"id":"3e27eb0c4421460c747a227e7bd63cb2"}` yet I still see nothing in the APM Web UI. I'm going to try to look for the ID `3e27eb0c4421460c747a227e7bd63cb2` somewhere. I'll post again if I find it anywhere.

**Comment by david-luna** [comment]
I do not see anything wrong in this log

this line
```
{"log.level":"trace","@timestamp":"2024-05-03T12:05:28.577Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","event.module":"apmclient","reqId":"08a56d5d3e89749ce116dd30188cd1f5","timeline":[[1.202958,"completePart gzipStream",null],[1.588833,"completePart intakeReq",null],[89.3285,"completePart intakeRes",null]],"bytesWritten":2373,"backoffDelayMs":0,"message":"conclude intake request: success"}
```
reveals that the http client received a successful response from the endpoint. 

To discard any other communication issue we should check if the URL configured in the agent is pointing to the APM server or any other component like a proxy. @Vectarian-Jorge could you please check it?

I ran my tests with the same node and agent version specified in the issue but a different APM server version (8.12.1). I'll try to run the tests with same APM server 7.17.8 to discard any version incompatibility

**Comment by david-luna** [comment]
Ran the test with
- Elastic cloud stack 7.17.8
- `elastic-apm-node@4.5.3`

slight modification of the server script to test more cases
```js
import './apm.js'; // Must go first
import express from 'express';

const port = 3000;
const app = express();

app.get('/reject', (_req, res) => {
	Promise.reject(new Error('Rejection')); // 1. This is unhandled so ti should be reported
	res.send('Hello World!');
});
app.get('/error', (_req, res) => {
	throw new Error('Exception'); // 2. This is handled by express, no error
});

app.listen(port, () => {
	console.log(`Example app listening on port ${port}`);
});

throw new Error('Boom'); // 3. This should also be reported, comment to test rejection (1)
```

The service errors appear in Kibana
![Screenshot 2024-05-10 at 12 05 45](https://github.com/elastic/apm-agent-nodejs/assets/999029/407c2e77-b705-4e30-93bc-bbed4a413bdf)

@Vectarian-Jorge I'm inclined to check the transit from the agent to the APM server. Have you checked for any proxy/nodes in between the app and the APM server?

**Comment by Vectarian-Jorge** [comment]
Thanks for checking all this @david-luna.

@PeterBero, you may need to check with Tomas about any possible proxy.
