### ISSUE TITLE
KafkaJS instrumentation throw exception on "tombstone message"

### ISSUE THREAD

**Issue by wilski-b** [elastic/apm-agent-nodejs#3980]
**Describe the bug**

Kafkajs support added in v4.5.2 throwing error for "tombstone messages" (messages with no payload value).

**To Reproduce**

1.  With APM enabled, using a kafkajs consumer, consume a tombstone message (message with null value) see script below.

**Expected behavior**

1. To be able to consume a "tombstone message" using KafkaJS and APM.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 18
- APM Server version: 8.9.1
- Agent version: 4.5.2

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Here is a script that reproduces the issue (note process.env's that must be set):
```
const apm = require('elastic-apm-node')

apm.start({
  secretToken: process.env.APM_TOKEN,
  serverUrl: process.env.APM_HOST,
  environment: process.env.ENV,
  captureBody: 'all',
})

const { Kafka } = require('kafkajs')

const kafka = new Kafka({
  clientId: 'test-app',
  brokers: [process.env.KAFKA_CLUSTER_ENDPOINTS],
})
const consumer = kafka.consumer({ groupId: 'my-group' })
consumer.on('consumer.crash', event => {
  const error = event?.payload?.error
  console.error(error)
  process.exit(1)
})
const producer = kafka.producer()
const TEST_TOPIC = 'test-topic'

/**
 *
 */
async function run() {
  await consumer.connect()
  await consumer.subscribe({ topics: [TEST_TOPIC] })
  await consumer.run({
    eachMessage: async ({ message }) => {
      console.log(`Received message with value: ${JSON.stringify(message.value?.toString())}`)
    },
  })

  await producer.connect()
  await producer.send({
    topic: TEST_TOPIC,
    messages: [
      { value: 'This message and others with a value not NULL work fine.' },
      { value: null }, // this message will end up causing elastic-apm-node to throw an uncaught exception from elastic-apm-node\lib\instrumentation\modules\kafkajs.js:141:41
    ],
  })
}

run()

```
error being thrown:
```
undefined,
  [cause]: TypeError: Cannot read properties of null (reading 'toString')
      at Runner.eachMessage (...\node_modules\elastic-apm-node\lib\instrumentation\modules\kafkajs.
js:141:41)
      at Runner.processEachMessage (...\node_modules\kafkajs\src\consumer\runner.js:231:20)
      at onBatch (...\node_modules\kafkajs\src\consumer\runner.js:447:20)
      at Runner.handleBatch (...\node_modules\kafkajs\src\consumer\runner.js:461:11)
      at handler (...\node_modules\kafkajs\src\consumer\runner.js:58:30)
      at ...\node_modules\kafkajs\src\consumer\worker.js:29:15
      at Object.run (...\node_modules\kafkajs\src\utils\sharedPromiseTo.js:14:17)
      at ...\node_modules\kafkajs\src\consumer\workerQueue.js:27:38
      at Array.forEach (<anonymous>)
      at Object.push (...\node_modules\kafkajs\src\consumer\workerQueue.js:27:13)
      at Object.start (...\node_modules\kafkajs\src\consumer\fetcher.js:62:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 0)
      at async Object.start (...\node_modules\kafkajs\src\consumer\fetchManager.js:74:9)
      at async ...\node_modules\kafkajs\src\consumer\runner.js:113:9
```

Agent config options: 
<details>
  <summary>Click to expand</summary>

```
  secretToken: process.env.APM_TOKEN,
  serverUrl: process.env.APM_HOST,
  environment: process.env.ENV,
  captureBody: 'all',
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
    "elastic-apm-node": "^4.5.2",
    "kafkajs": "^2.2.4",
```
</details>

**Comment by david-luna** [comment]
Hi @wilski-b 

Thanks for opening an issue and provide the required details. I can reproduce with the current test suite so its definitely a bug. I'm working on it right away :)

**Comment by wilski-b** [comment]
Thank you for the quick response @david-luna
