### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'propagateTraceContextHeaders')

### ISSUE THREAD

**Issue by qlp-mathias** [elastic/apm-agent-nodejs#4138]
https://github.com/elastic/apm-agent-nodejs/blob/b19a5d8e1fdc05946b7517b286592051fa06f210/lib/instrumentation/modules/%40aws-sdk/client-sns.js#L52

For some reason we ran into the case that `parentSpan` was null and the above line triggered an outage on one of our customer facing services.

![Screenshot 2024-07-15 at 13 11 48](https://github.com/user-attachments/assets/ae8e54c4-2fb6-4b52-b0c6-58e3e026b439)

**Comment by trentm** [comment]
Can repro with:

```
cd test/instrumentation/modules/@aws-sdk/fixtures
# ... setup other AWS envvars to use localstack
TEST_ENDPOINT=http://localhost:4566 node use-client-sns.js | ecslog
```

Log output:

```
[2024-07-30T17:14:23.324Z] ERROR (elastic-apm-node): useClientSNS rejected
    error: {
        "type": "TypeError",
        "message": "Cannot read properties of null (reading 'propagateTraceContextHeaders')",
        "stack_trace":
            TypeError: Cannot read properties of null (reading 'propagateTraceContextHeaders')
                at /Users/trentm/el/apm-agent-nodejs/lib/instrumentation/modules/@aws-sdk/client-sns.js:52:22
                at SNSClient.send (/Users/trentm/el/apm-agent-nodejs/node_modules/@smithy/smithy-client/dist-cjs/client.js:20:20)
                at SNSClient._wrappedSmithyClientSend (/Users/trentm/el/apm-agent-nodejs/lib/instrumentation/modules/@smithy/smithy-client.js:158:21)
                at useClientSNS (/Users/trentm/el/apm-agent-nodejs/test/instrumentation/modules/@aws-sdk/fixtures/use-client-sns.js:83:26)
    }
```
