### ISSUE TITLE
bug on require-in-the-middle with http.js

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#4249]
**Describe the bug**

It is trying to mock `http.js` instead of http`

```
Error: Cannot find module '/usr/src/app/modules/http.js'
      at webpackEmptyContext (/usr/src/app/worker.js:31:11)
      at Instrumentation.__webpack_modules__.97399.Instrumentation._patchModule (webpack://app/node_modules/elastic-apm-node/lib/instrumentation/index.js:12:9)
      at <anonymous> (webpack://app/node_modules/elastic-apm-node/lib/instrumentation/index.js:12:9)
      at Module.patchedRequire (webpack://app/node_modules/require-in-the-middle/index.js:65:1)
      at Module.Hook._require.Module.require (webpack://app/node_modules/require-in-the-middle/index.js:65:1)
      at require (node:internal/modules/helpers:135:16)
      at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/mongodb@6.8.0/node_modules/mongodb/src/utils.ts:5:1)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
      at Module.load (node:internal/modules/cjs/loader:1317:32)
      at Module._load (node:internal/modules/cjs/loader:1127:12)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
      at Module.require (node:internal/modules/cjs/loader:1339:12)
      at Module.patchedRequire (/usr/src/app/node_modules/.pnpm/require-in-the-middle@7.4.0/node_modules/require-in-the-middle/index.js:217:27)
      at Hook._require.Module.require (/usr/src/app/node_modules/.pnpm/require-in-the-middle@7.4.0/node_modules/require-in-the-middle/index.js:142:27)
      at Module.patchedRequire (webpack://app/node_modules/require-in-the-middle/index.js:65:1)
      at Module.Hook._require.Module.require (webpack://app/node_modules/require-in-the-middle/index.js:65:1)
      at require (node:internal/modules/helpers:135:16)
      at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/mongodb@6.8.0/node_modules/mongodb/src/operations/execute_operation.ts:27:1)
```

**To Reproduce**

Try to instrument mongodb and http

**Expected behavior**

it should work

**Environment (please complete the following information)**

- OS: [e.g. Linux]: docker
- Node.js version: node 22
- APM Server version: 4.7.3
- Agent version: not needed

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [x] Starting node with `-r elastic-apm-node/start`

"elastic-apm-node": "4.7.3",

**Comment by trentm** [comment]
@sibelius I'm not exactly sure what is going on there. One thing that would help is more of a repro -- including your webpack config, etc.  One question: does "/usr/src/app/worker.js" refer to application code running in a *Web Worker*?

Note that the APM agent generally does *not* work with bundled code. https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-webpack includes some notes on configuring webpack -- but it mostly involves using "externals" to have all modules external to the bundle.

**Comment by sibelius** [comment]
it is trying to instrument `http.js` instead of `http`

not sure why it is adding the `.js` extension to the `http` module

**Comment by trentm** [comment]
I don't know what "it" is here. Is this the built "worker.js" bundle? Are you able to show that file, or some of it? E.g. show line 31 where that stack trace is pointing.

**Comment by sibelius** [comment]
I will reopen when I get more info, tks

**Comment by trentm** [comment]
Okay, thanks.
