### ISSUE TITLE
Node.js 6 nighly tests are failing

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#710]
After we merged elastic/apm-agent-nodejs#700 which should have fixed the nightly tests, they keep failing on Node.js 6.

So far they have only run twice since the above mentioned PR was merged, but they failed both times. They failed however with two different errors:

From https://travis-ci.org/elastic/apm-agent-nodejs/jobs/463320504:

```
running: test/instrumentation/modules/apollo-server-express.js
TAP version 13
# POST /graphql
/home/travis/build/elastic/apm-agent-nodejs/lib/instrumentation/http-shared.js:86
  if (typeof v === 'string' || v instanceof url.URL) {
                                 ^
TypeError: Right-hand side of 'instanceof' is not an object
    at ensureUrl (/home/travis/build/elastic/apm-agent-nodejs/lib/instrumentation/http-shared.js:86:34)
    at Object.request (/home/travis/build/elastic/apm-agent-nodejs/lib/instrumentation/http-shared.js:110:34)
    at Server.<anonymous> (/home/travis/build/elastic/apm-agent-nodejs/test/instrumentation/modules/apollo-server-express.js:52:20)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at Server.emit (/home/travis/build/elastic/apm-agent-nodejs/lib/instrumentation/http-shared.js:55:19)
    at emitListeningNT (net.js:1284:10)
    at elasticAPMCallbackWrapper (/home/travis/build/elastic/apm-agent-nodejs/lib/instrumentation/index.js:201:27)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
/home/travis/build/elastic/apm-agent-nodejs/test/test.js:112
    if (err) throw err
             ^
```

From https://travis-ci.org/elastic/apm-agent-nodejs/jobs/462779258:

```
running: test/agent.js
TAP version 13
# #startTransaction()
Sending error to Elastic APM { id: 'f81d0d46a276feff8c16b060e8a82caf' }
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
/home/travis/build/elastic/apm-agent-nodejs/test/test.js:112
    if (err) throw err
             ^
```

**Comment by watson** [comment]
Fixed by #711
