### ISSUE TITLE
Support running DEBUG=true together with -r elastic-apm-node/start

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#960]
If the agent is started using the `-r` flag, and you try to set the environment variable `DEBUG=true`, the agent will throw the following exception:

```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at Agent.start (/Users/watson/code/node_modules/elastic-apm-node/lib/agent.js:141:24)
    at Object.<anonymous> (/Users/watson/code/node_modules/elastic-apm-node/start.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
```

The issue is that the [`_ancestors`](https://github.com/elastic/apm-agent-nodejs/blob/e1026382d8c6987137c00ffda83eb4e1acf292e6/lib/agent.js#L140) array contains `null` as the last element:

```js
[ '/Users/watson/code/node_modules/elastic-apm-node/index.js',
  '/Users/watson/code/node_modules/elastic-apm-node/start.js',
  null ]
```

**Comment by curtisjohnson1** [comment]
Hi! I'm happy to pick this up if you'd like? A filter on the `_ancestors` array to remove falsy values should do the trick.

**Comment by watson** [comment]
Unfortunately, I think we have to do a little more than just filtering the array. We're expecting the last element in the array to be the users' own file. We need the path to this file because we want to find the users' own `package.json` file so we can list for instance their dependencies. But in this case the agent is being required before the users' own code, so the last file in this array is the agent itself.

Possible solutions:
- Either we just accept that we can't get this information, and leave the infromation we were suppoesd to get from their `package.json` as un-set.
- Or we see if there's another way of getting this information - for example from the `process.argv` array 🤔

**Comment by curtisjohnson1** [comment]
No problem, I can pick this up.  We can obtain the information from the `process.argv` array and then set it to the `logger.trace`
